// packages/react/src/components/Banner.tsx
import { type ReactNode } from 'react'
import { CloseIcon } from '../icons.js'

export type BannerVariant = 'info' | 'success' | 'warn' | 'danger'

export interface BannerAction {
  label: string
  onClick: () => void
}

export interface BannerProps {
  variant?: BannerVariant
  title?: string
  children: ReactNode
  action?: BannerAction
  onDismiss?: () => void
}

export function Banner({ variant = 'info', title, children, action, onDismiss }: BannerProps) {
  const isUrgent = variant === 'danger' || variant === 'warn'
  return (
    <div
      className={`banner banner--${variant}`}
      role={isUrgent ? 'alert' : 'status'}
      aria-live={isUrgent ? 'assertive' : 'polite'}
      aria-atomic="true"
    >
      <div className="banner__body">
        {title && <span className="banner__title">{title}</span>}
        <span>{children}</span>
      </div>
      {action && (
        <button type="button" className="banner__action" onClick={action.onClick}>
          {action.label}
        </button>
      )}
      {onDismiss && (
        <button
          type="button"
          className="banner__dismiss icon-btn"
          onClick={onDismiss}
          aria-label="Dismiss banner"
        >
          <CloseIcon aria-hidden="true" />
        </button>
      )}
    </div>
  )
}

// packages/svelte/src/lib/components/Banner.svelte
<script context="module" lang="ts">
  export type BannerVariant = 'info' | 'success' | 'warn' | 'danger';
  export interface BannerAction {
    label: string;
    onClick: () => void;
  }
</script>

<script lang="ts">
  import CloseIcon from '../icons/CloseIcon.svelte';
  export let variant: BannerVariant = 'info';
  export let title: string | undefined = undefined;
  export let action: BannerAction | undefined = undefined;
  export let onDismiss: (() => void) | undefined = undefined;

  $: isUrgent = variant === 'danger' || variant === 'warn';
</script>

<div
  class="banner banner--{variant}"
  role={isUrgent ? 'alert' : 'status'}
  aria-live={isUrgent ? 'assertive' : 'polite'}
  aria-atomic="true"
>
  <div class="banner__body">
    {#if title}<span class="banner__title">{title}</span>{/if}
    <span><slot /></span>
  </div>
  {#if action}
    <button type="button" class="banner__action" on:click={action.onClick}>{action.label}</button>
  {/if}
  {#if onDismiss}
    <button type="button" class="banner__dismiss icon-btn" on:click={onDismiss} aria-label="Dismiss banner">
      <CloseIcon />
    </button>
  {/if}
</div>
