// packages/react/src/components/Combobox.tsx
import { useState, useRef, useEffect, useId } from 'react';
import type { ChangeEvent, KeyboardEvent } from 'react';

export interface ComboboxOption {
  value: string;
  label: string;
}

export interface ComboboxProps {
  options: ComboboxOption[];
  value?: string;
  onChange?: (value: string) => void;
  label?: string;
  placeholder?: string;
  id?: string;
  disabled?: boolean;
  className?: string;
}

export function Combobox({
  options,
  value,
  onChange,
  label,
  placeholder = 'Search…',
  id,
  disabled = false,
  className = '',
}: ComboboxProps) {
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const listboxId = `${inputId}-lb`;

  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [activeIdx, setActiveIdx] = useState(-1);

  const inputRef = useRef<HTMLInputElement>(null);
  const wrapperRef = useRef<HTMLDivElement>(null);

  const selectedOption = options.find((o) => o.value === value);

  const filtered =
    query.trim() === ''
      ? options
      : options.filter((o) => o.label.toLowerCase().includes(query.toLowerCase()));

  const activeOptionId =
    activeIdx >= 0 && filtered[activeIdx] ? `${listboxId}-opt-${activeIdx}` : undefined;

  useEffect(() => {
    if (!open) return;
    function handler(e: MouseEvent) {
      if (!wrapperRef.current?.contains(e.target as Node)) {
        setOpen(false);
        setQuery('');
      }
    }
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  function openList() {
    if (disabled) return;
    setQuery(selectedOption?.label ?? '');
    setActiveIdx(options.findIndex((o) => o.value === value));
    setOpen(true);
  }

  function pick(opt: ComboboxOption) {
    onChange?.(opt.value);
    setOpen(false);
    setQuery('');
    inputRef.current?.focus();
  }

  function onInputChange(e: ChangeEvent<HTMLInputElement>) {
    setQuery(e.target.value);
    setActiveIdx(-1);
    if (!open) setOpen(true);
  }

  function onKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (disabled) return;
    if (e.key === 'Escape') { setOpen(false); setQuery(''); return; }
    if (!open) {
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') { e.preventDefault(); openList(); }
      return;
    }
    if (e.key === 'ArrowDown') { e.preventDefault(); setActiveIdx((i) => Math.min(i + 1, filtered.length - 1)); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); setActiveIdx((i) => Math.max(i - 1, 0)); }
    else if (e.key === 'Home') { e.preventDefault(); setActiveIdx(0); }
    else if (e.key === 'End') { e.preventDefault(); setActiveIdx(filtered.length - 1); }
    else if (e.key === 'Enter') { e.preventDefault(); if (activeIdx >= 0 && filtered[activeIdx]) pick(filtered[activeIdx]); }
    else if (e.key === 'Tab') { setOpen(false); setQuery(''); }
  }

  const displayValue = open ? query : (selectedOption?.label ?? '');

  return (
    <div ref={wrapperRef} className={`combobox-wrapper ${className}`.trim()}>
      {label && <label htmlFor={inputId} className="sr-only">{label}</label>}
      <div className="combobox-field">
        <input
          ref={inputRef}
          id={inputId}
          role="combobox"
          aria-expanded={open}
          aria-controls={listboxId}
          aria-autocomplete="list"
          aria-activedescendant={activeOptionId}
          aria-label={label}
          autoComplete="off"
          spellCheck={false}
          disabled={disabled}
          placeholder={placeholder}
          value={displayValue}
          onChange={onInputChange}
          onFocus={openList}
          onKeyDown={onKeyDown}
          className="combobox-input"
        />
        <button
          type="button"
          tabIndex={-1}
          aria-hidden="true"
          className="combobox-chevron-btn"
          onClick={() => {
            if (open) { setOpen(false); setQuery(''); }
            else { inputRef.current?.focus(); openList(); }
          }}
        >
          <svg className={`select-chevron${open ? ' combobox-chevron-open' : ''}`} viewBox="0 0 16 16" aria-hidden="true" focusable="false">
            <path d="M4 6l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
          </svg>
        </button>
      </div>
      {open && (
        <ul id={listboxId} role="listbox" aria-label={label} className="select-listbox combobox-listbox">
          {filtered.length === 0 ? (
            <li className="combobox-empty">No results</li>
          ) : (
            filtered.map((opt, idx) => (
              <li
                key={opt.value}
                id={`${listboxId}-opt-${idx}`}
                role="option"
                aria-selected={opt.value === value}
                data-active={idx === activeIdx ? 'true' : undefined}
                className="select-option"
                onMouseDown={(e) => { e.preventDefault(); pick(opt); }}
                onMouseEnter={() => setActiveIdx(idx)}
              >
                {opt.label}
              </li>
            ))
          )}
        </ul>
      )}
    </div>
  );
}

// packages/svelte/src/lib/components/Combobox.svelte
<script module lang="ts">
  let counter = 0;
  export interface ComboboxOption { value: string; label: string; }
</script>

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';

  interface Props {
    options?: ComboboxOption[];
    value?: string | undefined;
    label?: string | undefined;
    placeholder?: string;
    id?: string | undefined;
    disabled?: boolean;
    class?: string;
    onchange?: (payload: string) => void;
  }

  let {
    options = [],
    value = undefined,
    label = undefined,
    placeholder = 'Search…',
    id = undefined,
    disabled = false,
    class: className = '',
    onchange,
  }: Props = $props();
  

  const uid = `dash-ui-cb-${++counter}`;
  let inputId = $derived(id ?? uid);
  let listboxId = $derived(`${inputId}-lb`);
  let open = $state(false);
  let query = $state('');
  let activeIdx = $state(-1);
  let inputEl: HTMLInputElement = $state();
  let wrapperEl: HTMLDivElement = $state();

  let selectedOption = $derived(options.find((o) => o.value === value));

  let filtered = $derived(query.trim() === ''
    ? options
    : options.filter((o) => o.label.toLowerCase().includes(query.toLowerCase())));

  let activeOptionId = $derived(activeIdx >= 0 && filtered[activeIdx]
    ? `${listboxId}-opt-${activeIdx}`
    : undefined);

  let displayValue = $derived(open ? query : (selectedOption?.label ?? ''));

  function openList() {
    if (disabled) return;
    query = selectedOption?.label ?? '';
    activeIdx = options.findIndex((o) => o.value === value);
    open = true;
  }

  function pick(opt: ComboboxOption) {
    onchange?.(opt.value);
    open = false;
    query = '';
    inputEl?.focus();
  }

  function onInputChange(e: Event) {
    query = (e.target as HTMLInputElement).value;
    activeIdx = -1;
    if (!open) open = true;
  }

  function onKeyDown(e: KeyboardEvent) {
    if (disabled) return;
    if (e.key === 'Escape') { open = false; query = ''; return; }
    if (!open) {
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') { e.preventDefault(); openList(); }
      return;
    }
    if (e.key === 'ArrowDown') { e.preventDefault(); activeIdx = Math.min(activeIdx + 1, filtered.length - 1); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); activeIdx = Math.max(activeIdx - 1, 0); }
    else if (e.key === 'Home') { e.preventDefault(); activeIdx = 0; }
    else if (e.key === 'End') { e.preventDefault(); activeIdx = filtered.length - 1; }
    else if (e.key === 'Enter') { e.preventDefault(); if (activeIdx >= 0 && filtered[activeIdx]) pick(filtered[activeIdx]); }
    else if (e.key === 'Tab') { open = false; query = ''; }
  }

  function handleOutside(e: MouseEvent) {
    if (open && !wrapperEl?.contains(e.target as Node)) { open = false; query = ''; }
  }

  onMount(() => document.addEventListener('mousedown', handleOutside));
  onDestroy(() => document.removeEventListener('mousedown', handleOutside));
</script>

<div class="combobox-wrapper {className}" bind:this={wrapperEl}>
  {#if label}<label for={inputId} class="sr-only">{label}</label>{/if}
  <div class="combobox-field">
    <input
      bind:this={inputEl}
      id={inputId}
      role="combobox"
      aria-expanded={open}
      aria-controls={listboxId}
      aria-autocomplete="list"
      aria-activedescendant={activeOptionId}
      aria-label={label}
      autocomplete="off"
      spellcheck="false"
      {disabled}
      {placeholder}
      value={displayValue}
      oninput={onInputChange}
      onfocus={openList}
      onkeydown={onKeyDown}
      class="combobox-input"
    />
    <button
      type="button"
      tabindex="-1"
      aria-hidden="true"
      class="combobox-chevron-btn"
      onclick={() => { if (open) { open = false; query = ''; } else { inputEl?.focus(); openList(); } }}
    >
      <svg class="select-chevron{open ? ' combobox-chevron-open' : ''}" viewBox="0 0 16 16" aria-hidden="true" focusable="false">
        <path d="M4 6l4 4 4-4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" fill="none" />
      </svg>
    </button>
  </div>
  {#if open}
    <ul id={listboxId} role="listbox" aria-label={label} class="select-listbox combobox-listbox">
      {#if filtered.length === 0}
        <li class="combobox-empty">No results</li>
      {:else}
        {#each filtered as opt, idx (opt.value)}
          <li
            id="{listboxId}-opt-{idx}"
            role="option"
            aria-selected={opt.value === value}
            data-active={idx === activeIdx ? 'true' : undefined}
            class="select-option"
            onmousedown={(e) => { e.preventDefault(); (() => pick(opt))(e); }}
            onmouseenter={() => { activeIdx = idx; }}
          >{opt.label}</li>
        {/each}
      {/if}
    </ul>
  {/if}
</div>
