// packages/react/src/components/CopyButton.tsx
import { useState, useCallback } from 'react';

const CopyIcon = () => (
  <svg viewBox="0 0 14 14" width="14" height="14" fill="none" aria-hidden="true" focusable={false}>
    <rect x="4" y="1" width="9" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.5" />
    <rect x="1" y="4" width="9" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.5" />
  </svg>
);

const CheckIcon = () => (
  <svg viewBox="0 0 14 14" width="14" height="14" fill="none" aria-hidden="true" focusable={false}>
    <path d="M2.5 7.5l3.5 3.5L12 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

export interface CopyButtonProps {
  text: string;
  label?: string;
}

export function CopyButton({ text, label = 'Copy' }: CopyButtonProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [text]);

  return (
    <button
      type="button"
      className={`copy-btn${copied ? ' copy-btn--done' : ''}`}
      aria-label={copied ? 'Copied!' : label}
      onClick={handleCopy}
    >
      {copied ? <CheckIcon /> : <CopyIcon />}
    </button>
  );
}

// packages/svelte/src/lib/components/CopyButton.svelte
<script lang="ts">
  export let text: string;
  export let label: string = 'Copy';

  let copied = false;
  let timer: ReturnType<typeof setTimeout>;

  function handleCopy() {
    navigator.clipboard.writeText(text).then(() => {
      copied = true;
      clearTimeout(timer);
      timer = setTimeout(() => { copied = false; }, 2000);
    });
  }
</script>

<button
  type="button"
  class="copy-btn {copied ? 'copy-btn--done' : ''}"
  aria-label={copied ? 'Copied!' : label}
  on:click={handleCopy}
>
  {#if copied}
    <svg viewBox="0 0 14 14" width="14" height="14" fill="none" aria-hidden="true" focusable="false">
      <path d="M2.5 7.5l3.5 3.5L12 3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
  {:else}
    <svg viewBox="0 0 14 14" width="14" height="14" fill="none" aria-hidden="true" focusable="false">
      <rect x="4" y="1" width="9" height="10" rx="1.5" stroke="currentColor" stroke-width="1.5"/>
      <rect x="1" y="4" width="9" height="10" rx="1.5" stroke="currentColor" stroke-width="1.5"/>
    </svg>
  {/if}
</button>
