// packages/react/src/components/FormActions.tsx
import type { HTMLAttributes, ReactNode } from 'react'

export interface FormActionsProps extends HTMLAttributes<HTMLDivElement> {
  children?: ReactNode
}

/**
 * Right-aligned action row that closes a form `<Card>` or modal body:
 * `display: flex; justify-content: flex-end; gap: 8px; margin-top: 16px`.
 * Typed equivalent of `<div className="form-actions">` from
 * `@w5-ui/tokens/dashboard.css`. Place destructive / cancel buttons on the
 * left, primary on the right.
 */
export function FormActions({ className = '', children, ...rest }: FormActionsProps) {
  return (
    <div className={`form-actions ${className}`.trim()} {...rest}>
      {children}
    </div>
  )
}

// packages/svelte/src/lib/components/FormActions.svelte
<script lang="ts">
  interface Props {
    class?: string;
    children?: import('svelte').Snippet;
  }

  let { class: className = '', children }: Props = $props();
</script>

<!--
  Right-aligned action row closing a form <Card> or modal body
  (display:flex; justify-content:flex-end; gap:8px; margin-top:16px).
  Typed equivalent of `<div class="form-actions">` from
  @w5-ui/tokens/dashboard.css.
-->
<div class="form-actions {className}">
  {@render children?.()}
</div>
