// packages/react/src/components/KVTable.tsx
import type { ReactNode } from 'react';

export interface KVRow {
  label: string;
  value: ReactNode;
}

export interface KVTableProps {
  rows: KVRow[];
  caption?: string;
}

export function KVTable({ rows, caption }: KVTableProps) {
  return (
    <table className="kv-table">
      {caption && <caption className="sr-only">{caption}</caption>}
      <tbody>
        {rows.map(({ label, value }) => (
          <tr key={label} className="kv-table__row">
            <th scope="row" className="kv-table__label">{label}</th>
            <td className="kv-table__value">{value}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

// packages/svelte/src/lib/components/KVTable.svelte
<script lang="ts">
  export let rows: Array<{ label: string; value: string; valueColor?: string }> = [];
  export let caption: string | undefined = undefined;
</script>

<table class="kv-table">
  {#if caption}
    <caption class="sr-only">{caption}</caption>
  {/if}
  <tbody>
    {#each rows as { label, value, valueColor }}
      <tr class="kv-table__row">
        <th scope="row" class="kv-table__label">{label}</th>
        <td class="kv-table__value" style={valueColor ? `color:${valueColor}` : undefined}>{value}</td>
      </tr>
    {/each}
  </tbody>
</table>
