// packages/react/src/components/Pill.tsx
import type { ReactNode, CSSProperties } from 'react'

export type PillVariant = 'success' | 'warn' | 'danger' | 'info' | 'neutral'

export interface PillProps {
  variant?: PillVariant
  showDot?: boolean
  children: ReactNode
  style?: CSSProperties
  className?: string
}

export function Pill({
  variant = 'neutral',
  showDot = true,
  children,
  style,
  className = '',
}: PillProps) {
  return (
    <span className={`pill pill-${variant} ${className}`.trim()} style={style}>
      {showDot && <span className="dot" aria-hidden="true" />}
      {children}
    </span>
  )
}

// packages/svelte/src/lib/components/Pill.svelte
<script lang="ts">
  export let variant: 'success' | 'warn' | 'danger' | 'info' | 'neutral' = 'neutral';
  export let showDot: boolean = true;
  let className = '';
  export { className as class };
  export let style: string = '';
</script>

<span class="pill pill-{variant} {className}" {style}>
  {#if showDot}<span class="dot" aria-hidden="true"></span>{/if}
  <slot />
</span>
