// packages/react/src/components/Skeleton.tsx
import type { CSSProperties } from 'react'

export type SkeletonVariant = 'text' | 'title' | 'stat' | 'circle' | 'block'

export interface SkeletonProps {
  variant?: SkeletonVariant
  width?: number | string
  height?: number | string
  className?: string
  style?: CSSProperties
  ariaLabel?: string
}

export function Skeleton({
  variant = 'text',
  width,
  height,
  className = '',
  style,
  ariaLabel = 'Loading',
}: SkeletonProps) {
  const variantClass = variant === 'block' ? '' : variant
  const mergedStyle: CSSProperties = {
    width: width ?? (variant === 'circle' ? height : undefined),
    height,
    ...style,
  }
  return (
    <span
      className={`skeleton ${variantClass} ${className}`.trim()}
      style={mergedStyle}
      role="status"
      aria-label={ariaLabel}
      aria-busy="true"
    />
  )
}

// packages/svelte/src/lib/components/Skeleton.svelte
<script lang="ts">
  export let variant: 'text' | 'title' | 'stat' | 'circle' | 'block' = 'text';
  export let width: string | number | undefined = undefined;
  export let height: string | number | undefined = undefined;
  let className = '';
  export { className as class };
  export let ariaLabel: string = 'Loading';

  $: variantClass = variant === 'block' ? '' : variant;
  $: w = width ?? (variant === 'circle' ? height : undefined);
  $: style = [
    w !== undefined ? `width:${typeof w === 'number' ? w + 'px' : w}` : '',
    height !== undefined ? `height:${typeof height === 'number' ? height + 'px' : height}` : '',
  ].filter(Boolean).join(';');
</script>

<span
  class="skeleton {variantClass} {className}"
  {style}
  role="status"
  aria-label={ariaLabel}
  aria-busy="true"
></span>
