// packages/react/src/components/Slider.tsx
import { useState, useId } from 'react'
import type { ChangeEvent, CSSProperties } from 'react'

export interface SliderProps {
  label?: string
  value?: number
  defaultValue?: number
  min?: number
  max?: number
  step?: number
  suffix?: string
  disabled?: boolean
  onChange?: (value: number) => void
  id?: string
  className?: string
}

export function Slider({
  label,
  value: valueProp,
  defaultValue = 0,
  min = 0,
  max = 100,
  step = 1,
  suffix,
  disabled = false,
  onChange,
  id,
  className = '',
}: SliderProps) {
  const generatedId = useId()
  const inputId = id ?? generatedId
  const [internalValue, setInternalValue] = useState(defaultValue)
  const value = valueProp !== undefined ? valueProp : internalValue

  const pct = max === min ? 0 : ((value - min) / (max - min)) * 100
  const fillStyle: CSSProperties = { '--slider-fill': `${pct}%` } as CSSProperties

  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    const next = Number(e.target.value)
    if (valueProp === undefined) setInternalValue(next)
    onChange?.(next)
  }

  return (
    <div className={`slider ${className}`.trim()}>
      {label && (
        <div className="slider__header">
          <label htmlFor={inputId} className="slider__label">
            {label}
          </label>
          <span className="slider__value" aria-live="polite">
            {value}
            {suffix && <span className="slider__suffix">{suffix}</span>}
          </span>
        </div>
      )}
      <input
        id={inputId}
        type="range"
        className="slider__track"
        min={min}
        max={max}
        step={step}
        value={value}
        disabled={disabled}
        style={fillStyle}
        onChange={handleChange}
        aria-label={label}
        aria-valuetext={suffix ? `${value} ${suffix}` : undefined}
      />
    </div>
  )
}

// packages/svelte/src/lib/components/Slider.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export let label: string | undefined = undefined;
  export let value: number = 0;
  export let min: number = 0;
  export let max: number = 100;
  export let step: number = 1;
  export let suffix: string | undefined = undefined;
  export let disabled: boolean = false;
  export let id: string | undefined = undefined;

  let counter = 0;
  const inputId = id ?? `slider-${counter++}`;
  const dispatch = createEventDispatcher<{ change: number }>();

  $: pct = max === min ? 0 : ((value - min) / (max - min)) * 100;

  function handleChange(e: Event) {
    value = Number((e.target as HTMLInputElement).value);
    dispatch('change', value);
  }
</script>

<div class="slider">
  {#if label}
    <div class="slider__header">
      <label for={inputId} class="slider__label">{label}</label>
      <span class="slider__value" aria-live="polite">
        {value}{#if suffix}<span class="slider__suffix">{suffix}</span>{/if}
      </span>
    </div>
  {/if}
  <input
    {id}
    type="range"
    class="slider__track"
    {min}
    {max}
    {step}
    {value}
    {disabled}
    style="--slider-fill:{pct}%"
    aria-label={label}
    aria-valuetext={suffix ? `${value} ${suffix}` : undefined}
    on:input={handleChange}
  />
</div>
