// packages/react/src/components/Spoiler.tsx
import { useState, useRef, useLayoutEffect, type ReactNode } from 'react';

export interface SpoilerProps {
  children: ReactNode;
  maxHeight?: number;
  showLabel?: string;
  hideLabel?: string;
  className?: string;
}

export function Spoiler({
  children,
  maxHeight = 80,
  showLabel = 'Show more',
  hideLabel = 'Show less',
  className,
}: SpoilerProps) {
  const [expanded, setExpanded] = useState(false);
  const [clipped, setClipped] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    const el = ref.current;
    if (el) setClipped(el.scrollHeight > maxHeight);
  }, [maxHeight]);

  return (
    <div className={`spoiler${className ? ' ' + className : ''}`}>
      <div className="spoiler-outer" style={{ position: 'relative' }}>
        <div
          ref={ref}
          style={!expanded && clipped ? { maxHeight, overflow: 'hidden' } : undefined}
        >
          {children}
        </div>
        {!expanded && clipped && <div className="spoiler-fade" aria-hidden="true" />}
      </div>
      {clipped && (
        <button
          type="button"
          className="spoiler-toggle"
          aria-expanded={expanded}
          onClick={() => setExpanded((v) => !v)}
        >
          {expanded ? hideLabel : showLabel}
        </button>
      )}
    </div>
  );
}

// packages/svelte/src/lib/components/Spoiler.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let maxHeight: number = 80;
  export let showLabel: string = 'Show more';
  export let hideLabel: string = 'Show less';
  let klass: string = '';
  export { klass as class };

  let expanded = false;
  let clipped = false;
  let bodyEl: HTMLDivElement;

  onMount(() => {
    if (bodyEl) clipped = bodyEl.scrollHeight > maxHeight;
  });
</script>

<div class="spoiler {klass}">
  <div class="spoiler-outer" style="position:relative">
    <div
      bind:this={bodyEl}
      style={!expanded && clipped ? `max-height:${maxHeight}px;overflow:hidden` : undefined}
    >
      <slot />
    </div>
    {#if !expanded && clipped}
      <div class="spoiler-fade" aria-hidden="true" />
    {/if}
  </div>
  {#if clipped}
    <button
      type="button"
      class="spoiler-toggle"
      aria-expanded={expanded}
      on:click={() => (expanded = !expanded)}
    >
      {expanded ? hideLabel : showLabel}
    </button>
  {/if}
</div>
