// packages/react/src/components/StackedProgress.tsx
export interface StackedProgressSegment {
  label: string
  value: number
  color: string
}

export interface StackedProgressProps {
  segments: StackedProgressSegment[]
  total?: number
  ariaLabel?: string
  showLegend?: boolean
}

export function StackedProgress({
  segments,
  total,
  ariaLabel,
  showLegend = true,
}: StackedProgressProps) {
  const sum = total ?? segments.reduce((acc, s) => acc + s.value, 0)
  const text =
    ariaLabel ?? segments.map((s) => `${s.label} ${Math.round((s.value / sum) * 100)}%`).join(', ')
  return (
    <div className="sp" role="img" aria-label={text}>
      <div className="sp-bar" aria-hidden="true">
        {segments.map(({ label, value, color }) => (
          <div
            key={label}
            className="sp-seg"
            style={{ width: `${(value / sum) * 100}%`, background: color }}
          />
        ))}
      </div>
      {showLegend && (
        <div className="sp-legend" aria-hidden="true">
          {segments.map(({ label, value, color }) => (
            <span key={label} className="sp-item">
              <span className="sp-dot" style={{ background: color }} />
              {label}
              <span className="sp-pct">{Math.round((value / sum) * 100)}%</span>
            </span>
          ))}
        </div>
      )}
    </div>
  )
}

// packages/svelte/src/lib/components/StackedProgress.svelte
<script lang="ts">
  export interface StackedProgressSegment {
    label: string;
    value: number;
    color: string;
  }
  export let segments: StackedProgressSegment[];
  export let total: number | undefined = undefined;
  export let ariaLabel: string | undefined = undefined;
  export let showLegend: boolean = true;
  $: sum = total ?? segments.reduce((a, s) => a + s.value, 0);
  $: text = ariaLabel ?? segments.map((s) => `${s.label} ${Math.round((s.value / sum) * 100)}%`).join(', ');
</script>

<div class="sp" role="img" aria-label={text}>
  <div class="sp-bar" aria-hidden="true">
    {#each segments as { label, value, color }}
      <div class="sp-seg" style="width:{((value / sum) * 100).toFixed(2)}%;background:{color}" />
    {/each}
  </div>
  {#if showLegend}
    <div class="sp-legend" aria-hidden="true">
      {#each segments as { label, value, color }}
        <span class="sp-item">
          <span class="sp-dot" style="background:{color}" />
          {label}
          <span class="sp-pct">{Math.round((value / sum) * 100)}%</span>
        </span>
      {/each}
    </div>
  {/if}
</div>
