// packages/react/src/components/Stepper.tsx
export interface StepperStep {
  id: string;
  label: string;
}

export interface StepperProps {
  steps: StepperStep[];
  active: string;
  className?: string;
}

export function Stepper({ steps, active, className = '' }: StepperProps) {
  const activeIdx = steps.findIndex(s => s.id === active);
  return (
    <nav aria-label="Progress" className={`stepper ${className}`.trim()}>
      <ol className="stepper__list">
        {steps.map((step, idx) => {
          const isActive = step.id === active;
          const isDone = idx < activeIdx;
          const state = isActive ? 'active' : isDone ? 'done' : 'upcoming';
          return (
            <li key={step.id} className={`stepper__item stepper__item--${state}`}>
              <span className="stepper__num" aria-hidden="true">
                {isDone ? (
                  <svg viewBox="0 0 12 12" width="12" height="12" fill="none">
                    <path d="M2 6l3 3 5-5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                ) : (
                  idx + 1
                )}
              </span>
              {isDone && <span className="sr-only">completed: </span>}
              <span className="stepper__label" {...(isActive ? { 'aria-current': 'step' as const } : {})}>
                {step.label}
              </span>
            </li>
          );
        })}
      </ol>
    </nav>
  );
}

// packages/svelte/src/lib/components/Stepper.svelte
<script context="module" lang="ts">
  export interface StepperStep {
    id: string;
    label: string;
  }
</script>

<script lang="ts">
  export let steps: StepperStep[];
  export let active: string;
  let className = '';
  export { className as class };

  $: activeIdx = steps.findIndex(s => s.id === active);
</script>

<nav aria-label="Progress" class="stepper {className}">
  <ol class="stepper__list">
    {#each steps as step, idx}
      {@const isActive = step.id === active}
      {@const isDone = idx < activeIdx}
      {@const state = isActive ? 'active' : isDone ? 'done' : 'upcoming'}
      <li class="stepper__item stepper__item--{state}">
        <span class="stepper__num" aria-hidden="true">
          {#if isDone}
            <svg viewBox="0 0 12 12" width="12" height="12" fill="none">
              <path d="M2 6l3 3 5-5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
          {:else}
            {idx + 1}
          {/if}
        </span>
        {#if isDone}<span class="sr-only">completed: </span>{/if}
        <span class="stepper__label" aria-current={isActive ? 'step' : undefined}>
          {step.label}
        </span>
      </li>
    {/each}
  </ol>
</nav>
