// packages/react/src/components/Tabs.tsx
import { useRef, type HTMLAttributes, type KeyboardEvent, type ReactNode } from 'react';

export interface TabItem {
  id: string;
  label: ReactNode;
  badge?: ReactNode;
}

export interface TabPanelProps extends HTMLAttributes<HTMLDivElement> {
  id: string;
  active: string;
  children?: ReactNode;
}

export function TabPanel({ id, active, children, ...rest }: TabPanelProps) {
  const isActive = id === active;
  return (
    <div
      role="tabpanel"
      id={`tabpanel-${id}`}
      aria-labelledby={`tab-${id}`}
      hidden={!isActive}
      tabIndex={0}
      {...rest}
    >
      {isActive ? children : null}
    </div>
  );
}

export interface TabsProps {
  items: TabItem[];
  active: string;
  onChange?: (id: string) => void;
  ariaLabel?: string;
}

export function Tabs({ items, active, onChange, ariaLabel }: TabsProps) {
  const refs = useRef<(HTMLButtonElement | null)[]>([]);

  const focusAt = (idx: number) => {
    const next = items[(idx + items.length) % items.length];
    if (!next) return;
    onChange?.(next.id);
    refs.current[(idx + items.length) % items.length]?.focus();
  };

  const onKey = (e: KeyboardEvent<HTMLButtonElement>, i: number) => {
    if (e.key === 'ArrowRight') { e.preventDefault(); focusAt(i + 1); }
    else if (e.key === 'ArrowLeft') { e.preventDefault(); focusAt(i - 1); }
    else if (e.key === 'Home') { e.preventDefault(); focusAt(0); }
    else if (e.key === 'End') { e.preventDefault(); focusAt(items.length - 1); }
  };

  return (
    <div className="tabs" role="tablist" aria-label={ariaLabel}>
      {items.map((t, i) => {
        const selected = t.id === active;
        return (
          <button
            key={t.id}
            ref={(el) => { refs.current[i] = el; }}
            type="button"
            role="tab"
            id={`tab-${t.id}`}
            aria-selected={selected}
            aria-controls={`tabpanel-${t.id}`}
            tabIndex={selected ? 0 : -1}
            className={`tab ${selected ? 'active' : ''}`}
            onClick={() => onChange?.(t.id)}
            onKeyDown={(e) => onKey(e, i)}
          >
            {t.label}
            {t.badge !== undefined && <span className="badge">{t.badge}</span>}
          </button>
        );
      })}
    </div>
  );
}

// packages/svelte/src/lib/components/Tabs.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  export interface TabItem { id: string; label: string; badge?: string | number }
  export let items: TabItem[] = [];
  export let active: string;
  export let ariaLabel: string | undefined = undefined;
  const dispatch = createEventDispatcher<{ change: string }>();

  let buttons: (HTMLButtonElement | null)[] = [];

  function select(idx: number) {
    const next = items[(idx + items.length) % items.length];
    if (!next) return;
    active = next.id;
    dispatch('change', next.id);
    buttons[(idx + items.length) % items.length]?.focus();
  }

  function onKey(e: KeyboardEvent, i: number) {
    if (e.key === 'ArrowRight') { e.preventDefault(); select(i + 1); }
    else if (e.key === 'ArrowLeft') { e.preventDefault(); select(i - 1); }
    else if (e.key === 'Home') { e.preventDefault(); select(0); }
    else if (e.key === 'End') { e.preventDefault(); select(items.length - 1); }
  }
</script>

<div class="tabs" role="tablist" aria-label={ariaLabel}>
  {#each items as t, i (t.id)}
    <button
      bind:this={buttons[i]}
      type="button"
      class="tab {t.id === active ? 'active' : ''}"
      role="tab"
      id="tab-{t.id}"
      aria-selected={t.id === active}
      aria-controls="tabpanel-{t.id}"
      tabindex={t.id === active ? 0 : -1}
      on:click={() => { active = t.id; dispatch('change', t.id); }}
      on:keydown={(e) => onKey(e, i)}
    >
      {t.label}
      {#if t.badge !== undefined}<span class="badge">{t.badge}</span>{/if}
    </button>
  {/each}
</div>
