// packages/react/src/components/TagInput.tsx
import { useId, useRef, useState } from 'react'
import type { KeyboardEvent } from 'react'
import { Tag } from './Tag.js'

export interface TagInputProps {
  label?: string
  value?: string[]
  defaultValue?: string[]
  onChange?: (tags: string[]) => void
  placeholder?: string
  id?: string
  disabled?: boolean
  className?: string
}

export function TagInput({
  label,
  value: valueProp,
  defaultValue = [],
  onChange,
  placeholder = 'Type and press Enter…',
  id,
  disabled = false,
  className = '',
}: TagInputProps) {
  const gid = useId()
  const inputId = id ?? gid
  const listId = `${inputId}-list`

  const [internal, setInternal] = useState<string[]>(defaultValue)
  const [draft, setDraft] = useState('')
  const inputRef = useRef<HTMLInputElement>(null)

  const tags = valueProp !== undefined ? valueProp : internal

  function commit(next: string[]) {
    if (valueProp === undefined) setInternal(next)
    onChange?.(next)
  }

  function addTag(raw: string) {
    const trimmed = raw.trim()
    if (!trimmed || tags.includes(trimmed)) return
    commit([...tags, trimmed])
    setDraft('')
  }

  function removeTag(index: number) {
    commit(tags.filter((_, i) => i !== index))
  }

  function handleKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter' || e.key === ',' || e.key === 'Tab') {
      if (draft.trim()) {
        e.preventDefault()
        addTag(draft)
      }
    } else if (e.key === 'Backspace' && draft === '' && tags.length > 0) {
      removeTag(tags.length - 1)
    }
  }

  return (
    <div className={`tag-input-wrapper${className ? ` ${className}` : ''}`}>
      {label && (
        <label htmlFor={inputId} className="tag-input__label">
          {label}
        </label>
      )}
      <div
        id={listId}
        role="group"
        aria-label={label ?? 'Tags'}
        className={`tag-input${disabled ? ' tag-input--disabled' : ''}`}
        onClick={() => inputRef.current?.focus()}
      >
        {tags.map((t, i) => (
          <Tag key={t} label={t} onRemove={disabled ? undefined : () => removeTag(i)} />
        ))}
        <input
          ref={inputRef}
          id={inputId}
          type="text"
          className="tag-input__field"
          value={draft}
          disabled={disabled}
          placeholder={tags.length === 0 ? placeholder : ''}
          aria-label={label ?? 'Add tag'}
          autoComplete="off"
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={handleKeyDown}
          onBlur={() => {
            if (draft.trim()) addTag(draft)
          }}
        />
      </div>
    </div>
  )
}

// packages/svelte/src/lib/components/TagInput.svelte
<script module lang="ts">
  let counter = 0;
</script>

<script lang="ts">
  

  interface Props {
    label?: string | undefined;
    value?: string[];
    placeholder?: string;
    disabled?: boolean;
    class?: string;
    onchange?: (payload: string[]) => void;
  }

  let {
    label = undefined,
    value = $bindable([]),
    placeholder = 'Type and press Enter…',
    disabled = false,
    class: klass = '',
    onchange,
  }: Props = $props();
  const uid = `dash-ui-tag-input-${++counter}`;

  let draft = $state('');
  let inputEl = $state<HTMLInputElement | undefined>(undefined);

  function addTag(raw: string) {
    const trimmed = raw.trim();
    if (!trimmed || value.includes(trimmed)) return;
    value = [...value, trimmed];
    draft = '';
    onchange?.(value);
  }

  function removeTag(index: number) {
    value = value.filter((_, i) => i !== index);
    onchange?.(value);
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' || e.key === ',' || e.key === 'Tab') {
      if (draft.trim()) {
        e.preventDefault();
        addTag(draft);
      }
    } else if (e.key === 'Backspace' && draft === '' && value.length > 0) {
      removeTag(value.length - 1);
    }
  }

  function handleBlur() {
    if (draft.trim()) addTag(draft);
  }
</script>

<div class="tag-input-wrapper {klass}">
  {#if label}
    <label for={uid} class="tag-input__label">{label}</label>
  {/if}
  <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions - group container focuses input on click -->
  <div
    role="group"
    aria-label={label ?? 'Tags'}
    class="tag-input{disabled ? ' tag-input--disabled' : ''}"
    onclick={() => inputEl?.focus()}
  >
    {#each value as tag, i}
      <span class="tag">
        <span class="tag__label">{tag}</span>
        {#if !disabled}
          <button
            type="button"
            class="tag__remove"
            aria-label="Remove {tag}"
            onclick={(e) => { e.stopPropagation(); (() => removeTag(i))(); }}
          >
            <svg viewBox="0 0 10 10" width="10" height="10" fill="none" aria-hidden="true" focusable="false">
              <path d="M2 2l6 6M8 2l-6 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
            </svg>
          </button>
        {/if}
      </span>
    {/each}
    <input
      bind:this={inputEl}
      id={uid}
      type="text"
      class="tag-input__field"
      bind:value={draft}
      {disabled}
      placeholder={value.length === 0 ? placeholder : ''}
      aria-label={label ?? 'Add tag'}
      autocomplete="off"
      onkeydown={handleKeyDown}
      onblur={handleBlur}
    />
  </div>
</div>
