// packages/react/src/components/Toast.tsx
import { useState, useEffect } from 'react';
import { CloseIcon } from '../icons.js';

export type ToastVariant = 'success' | 'info' | 'warn' | 'danger';

interface ToastItem {
  id: string;
  message: string;
  variant: ToastVariant;
}

type Listener = (item: ToastItem) => void;
const listeners = new Set<Listener>();
let seq = 0;

export const toast = {
  show(message: string, variant: ToastVariant = 'info') {
    const item: ToastItem = { id: String(++seq), message, variant };
    listeners.forEach((l) => l(item));
  },
  success: (msg: string) => toast.show(msg, 'success'),
  warn: (msg: string) => toast.show(msg, 'warn'),
  danger: (msg: string) => toast.show(msg, 'danger'),
  info: (msg: string) => toast.show(msg, 'info'),
};

export function Toaster() {
  const [items, setItems] = useState<ToastItem[]>([]);

  useEffect(() => {
    const add = (item: ToastItem) => {
      setItems((prev) => [...prev, item]);
      setTimeout(() => remove(item.id), 4000);
    };
    listeners.add(add);
    return () => { listeners.delete(add); };
  }, []);

  function remove(id: string) {
    setItems((prev) => prev.filter((t) => t.id !== id));
  }

  return (
    <div
      className="toaster"
      role="log"
      aria-label="Notifications"
      aria-live="polite"
      aria-atomic="false"
    >
      {items.map((item) => (
        <div
          key={item.id}
          className={`toast toast-${item.variant}`}
          role={item.variant === 'danger' ? 'alert' : 'status'}
        >
          <span className="toast-msg">{item.message}</span>
          <button
            type="button"
            className="toast-dismiss icon-btn"
            onClick={() => remove(item.id)}
            aria-label="Dismiss notification"
          >
            <CloseIcon aria-hidden="true" />
          </button>
        </div>
      ))}
    </div>
  );
}

// packages/svelte/src/lib/components/Toast.svelte
<script context="module" lang="ts">
  import { writable } from 'svelte/store';

  export type ToastVariant = 'success' | 'info' | 'warn' | 'danger';

  interface ToastItem {
    id: string;
    message: string;
    variant: ToastVariant;
  }

  const store = writable<ToastItem[]>([]);
  let seq = 0;

  function dismiss(id: string) {
    store.update((prev) => prev.filter((t) => t.id !== id));
  }

  export const toast = {
    show(message: string, variant: ToastVariant = 'info') {
      const id = String(++seq);
      store.update((prev) => [...prev, { id, message, variant }]);
      setTimeout(() => dismiss(id), 4000);
    },
    success: (msg: string) => toast.show(msg, 'success'),
    warn: (msg: string) => toast.show(msg, 'warn'),
    danger: (msg: string) => toast.show(msg, 'danger'),
    info: (msg: string) => toast.show(msg, 'info'),
  };
</script>

<script lang="ts">
  // store and dismiss are in module scope — accessible in template via $store
</script>

<div class="toaster" role="log" aria-label="Notifications" aria-live="polite" aria-atomic="false">
  {#each $store as item (item.id)}
    <div class="toast toast-{item.variant}" role={item.variant === 'danger' ? 'alert' : 'status'}>
      <span class="toast-msg">{item.message}</span>
      <button
        type="button"
        class="toast-dismiss icon-btn"
        on:click={() => dismiss(item.id)}
        aria-label="Dismiss notification"
      >
        <svg viewBox="0 0 14 14" width="14" height="14" aria-hidden="true" focusable="false">
          <path d="M2 2l10 10M12 2L2 12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
        </svg>
      </button>
    </div>
  {/each}
</div>
