// packages/react/src/components/Toggle.tsx
import type { ReactNode } from 'react';

export interface ToggleProps {
  on: boolean;
  onToggle?: () => void;
  ariaLabel?: string;
}

export function Toggle({ on, onToggle, ariaLabel }: ToggleProps) {
  return (
    <span
      role="switch"
      aria-checked={on}
      aria-label={ariaLabel}
      tabIndex={0}
      onClick={onToggle}
      onKeyDown={(e) => {
        if (e.key === ' ' || e.key === 'Enter') {
          e.preventDefault();
          onToggle?.();
        }
      }}
      className={`toggle-track ${on ? 'on' : 'off'}`}
    >
      <span className="knob" />
    </span>
  );
}

export interface RowToggleProps {
  title: string;
  description: string;
  on: boolean;
  onToggle?: () => void;
}

export function RowToggle({ title, description, on, onToggle }: RowToggleProps) {
  return (
    <div className="row-toggle">
      <div className="info">
        <div className="t">{title}</div>
        <div className="d">{description}</div>
      </div>
      <Toggle on={on} onToggle={onToggle} ariaLabel={title} />
    </div>
  );
}

export interface RowToggleListProps {
  items: { title: string; description: string }[];
  state: Record<string, boolean>;
  onToggle: (title: string) => void;
}

export function RowToggleList({ items, state, onToggle }: RowToggleListProps) {
  return (
    <>
      {items.map((it) => (
        <RowToggle
          key={it.title}
          title={it.title}
          description={it.description}
          on={!!state[it.title]}
          onToggle={() => onToggle(it.title)}
        />
      ))}
    </>
  );
}

// packages/svelte/src/lib/components/Toggle.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  export let on: boolean = false;
  export let ariaLabel: string | undefined = undefined;
  const dispatch = createEventDispatcher<{ toggle: boolean }>();
  function flip() {
    on = !on;
    dispatch('toggle', on);
  }
</script>

<span
  role="switch"
  aria-checked={on}
  aria-label={ariaLabel}
  tabindex="0"
  class="toggle-track {on ? 'on' : 'off'}"
  on:click={flip}
  on:keydown={(e) => { if (e.key === ' ' || e.key === 'Enter') { e.preventDefault(); flip(); } }}
>
  <span class="knob"></span>
</span>
