// packages/react/src/components/TreeBrowser.tsx
import { useCallback, useRef, useState } from 'react'
import type { HTMLAttributes, KeyboardEvent, ReactNode } from 'react'

/**
 * TreeBrowser - React mirror of the Svelte `@w5-ui/svelte` component
 * (instructure-ui `ui-tree-browser`, medium size, `folderTree` variant).
 * Styling lives in `@w5-ui/tokens/dashboard.css` under `.tree-browser*`;
 * see the Svelte source for the token mapping. API mirrors 1:1.
 */

export interface TreeBrowserCollection {
  id: string
  name: string
  descriptor?: string
  collections?: string[]
  items?: string[]
}

export interface TreeBrowserItem {
  id: string
  name: string
  descriptor?: string
}

export type TreeBrowserNodeType = 'collection' | 'item'

export interface TreeBrowserRowContext {
  id: string
  type: TreeBrowserNodeType
  name: string
}

export interface TreeBrowserProps extends Omit<HTMLAttributes<HTMLUListElement>, 'onSelect'> {
  collections: Record<string, TreeBrowserCollection>
  items?: Record<string, TreeBrowserItem>
  rootId: string
  /** Uncontrolled initial expansion. Ignored when `expanded` is set. */
  defaultExpanded?: string[]
  /** Controlled expansion set. Pair with `onToggle`. */
  expanded?: string[]
  onToggle?: (id: string) => void
  selected?: string
  onSelect?: (id: string, type: TreeBrowserNodeType) => void
  size?: 'medium'
  variant?: 'folderTree' | 'indent'
  label?: string
  /** Per-row leading icon; overrides the built-in folder/file glyphs. */
  renderIcon?: (ctx: TreeBrowserRowContext) => ReactNode
  /** Trailing badge (missing-file marker, count, etc.). */
  renderBadge?: (ctx: TreeBrowserRowContext) => ReactNode
}

interface FlatNode {
  id: string
  type: TreeBrowserNodeType
  hasChildren: boolean
  parentId: string | undefined
}

function childIds(
  collections: Record<string, TreeBrowserCollection>,
  id: string,
): { collections: string[]; items: string[] } {
  const node = collections[id]
  return { collections: node?.collections ?? [], items: node?.items ?? [] }
}

function hasChildren(collections: Record<string, TreeBrowserCollection>, id: string): boolean {
  const { collections: c, items } = childIds(collections, id)
  return c.length > 0 || items.length > 0
}

/** Root collection's direct children (folders then items). */
export function topLevelIds(
  collections: Record<string, TreeBrowserCollection>,
  rootId: string,
): string[] {
  const root = collections[rootId]
  if (!root) return []
  return [...(root.collections ?? []), ...(root.items ?? [])]
}

function flattenVisible(
  collections: Record<string, TreeBrowserCollection>,
  rootId: string,
  expanded: Set<string>,
): FlatNode[] {
  const out: FlatNode[] = []
  const seen = new Set<string>([rootId])
  const walk = (collectionId: string): void => {
    const { collections: cols, items } = childIds(collections, collectionId)
    for (const childId of cols) {
      if (seen.has(childId)) continue
      seen.add(childId)
      const childHasChildren = hasChildren(collections, childId)
      out.push({
        id: childId,
        type: 'collection',
        hasChildren: childHasChildren,
        parentId: collectionId,
      })
      if (childHasChildren && expanded.has(childId)) walk(childId)
    }
    for (const itemId of items) {
      if (seen.has(itemId)) continue
      seen.add(itemId)
      out.push({ id: itemId, type: 'item', hasChildren: false, parentId: collectionId })
    }
  }
  walk(rootId)
  return out
}

function FolderIcon({ open }: { open: boolean }) {
  return (
    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" width="16" height="16">
      {open ? (
        <path
          d="M1.5 5.5h13l-1.6 7A1 1 0 0 1 11.9 13H3.4a1 1 0 0 1-1-.8L1 4.2a1 1 0 0 1 1-1.2h3.2a1 1 0 0 1 .8.4l.9 1.2H13a1 1 0 0 1 1 1v.9"
          stroke="currentColor"
          strokeWidth="1.2"
          strokeLinejoin="round"
        />
      ) : (
        <path
          d="M1.5 3.8a1 1 0 0 1 1-1h3.2a1 1 0 0 1 .8.4l.9 1.2h6.1a1 1 0 0 1 1 1v6.3a1 1 0 0 1-1 1H2.5a1 1 0 0 1-1-1V3.8Z"
          stroke="currentColor"
          strokeWidth="1.2"
          strokeLinejoin="round"
        />
      )}
    </svg>
  )
}

function FileIcon() {
  return (
    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" width="16" height="16">
      <path
        d="M4 1.5h5L13 5.5v9a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-12a1 1 0 0 1 1-1Z"
        stroke="currentColor"
        strokeWidth="1.2"
        strokeLinejoin="round"
      />
      <path d="M9 1.5v4h4" stroke="currentColor" strokeWidth="1.2" strokeLinejoin="round" />
    </svg>
  )
}

interface NodeProps {
  id: string
  type: TreeBrowserNodeType
  collections: Record<string, TreeBrowserCollection>
  items: Record<string, TreeBrowserItem>
  expanded: Set<string>
  selected: string | undefined
  focusedId: string
  variant: 'folderTree' | 'indent'
  renderIcon?: (ctx: TreeBrowserRowContext) => ReactNode
  renderBadge?: (ctx: TreeBrowserRowContext) => ReactNode
}

function TreeBrowserNode(props: NodeProps) {
  const { id, type, collections, items, expanded, selected, focusedId, renderIcon, renderBadge } =
    props
  const isCollection = type === 'collection'
  const node = isCollection ? collections[id] : items[id]
  const name = node?.name ?? ''
  const descriptor = node?.descriptor
  const nodeHasChildren = isCollection && hasChildren(collections, id)
  const isExpanded = expanded.has(id)
  const isSelected = selected === id
  const children = isCollection ? childIds(collections, id) : { collections: [], items: [] }
  const ctx: TreeBrowserRowContext = { id, type, name }

  return (
    <li
      role="treeitem"
      aria-expanded={nodeHasChildren ? isExpanded : undefined}
      aria-selected={isSelected}
      tabIndex={focusedId === id ? 0 : -1}
      data-tree-id={id}
      data-type={type}
      className="tree-browser__item"
    >
      <div className={`tree-browser__row${isSelected ? ' tree-browser__row--selected' : ''}`}>
        {nodeHasChildren ? (
          <svg
            className={`tree-browser__chevron${isExpanded ? ' tree-browser__chevron--open' : ''}`}
            viewBox="0 0 12 12"
            fill="none"
            aria-hidden="true"
          >
            <path
              d="M4 2l4 4-4 4"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        ) : (
          <span className="tree-browser__indent" aria-hidden="true" />
        )}
        <span className="tree-browser__icon" aria-hidden="true">
          {renderIcon ? (
            renderIcon(ctx)
          ) : isCollection ? (
            <FolderIcon open={isExpanded} />
          ) : (
            <FileIcon />
          )}
        </span>
        <span className="tree-browser__names">
          <span className="tree-browser__name">{name}</span>
          {descriptor && <span className="tree-browser__descriptor">{descriptor}</span>}
        </span>
        {renderBadge && <span className="tree-browser__badge">{renderBadge(ctx)}</span>}
      </div>
      {isCollection && nodeHasChildren && isExpanded && (
        <ul role="group" className="tree-browser__group">
          {children.collections.map((childId) => (
            <TreeBrowserNode key={childId} {...props} id={childId} type="collection" />
          ))}
          {children.items.map((itemId) => (
            <TreeBrowserNode key={itemId} {...props} id={itemId} type="item" />
          ))}
        </ul>
      )}
    </li>
  )
}

export function TreeBrowser({
  collections,
  items = {},
  rootId,
  defaultExpanded = [],
  expanded,
  onToggle,
  selected,
  onSelect,
  size: _size = 'medium',
  variant = 'folderTree',
  label,
  renderIcon,
  renderBadge,
  className = '',
  ...rest
}: TreeBrowserProps) {
  const isControlled = expanded !== undefined
  const [internalExpanded, setInternalExpanded] = useState<Set<string>>(
    () => new Set(defaultExpanded),
  )
  const expandedSet = isControlled ? new Set(expanded) : internalExpanded
  // Selection: controlled via `selected` when provided, otherwise tracked
  // internally so a click marks the row (parity with the Svelte bindable).
  const [internalSelected, setInternalSelected] = useState<string | undefined>(selected)
  const effectiveSelected = selected !== undefined ? selected : internalSelected
  const [focusedId, setFocusedId] = useState<string>(
    () => flattenVisible(collections, rootId, new Set(defaultExpanded))[0]?.id ?? '',
  )
  const rootRef = useRef<HTMLUListElement>(null)

  const toggle = useCallback(
    (id: string) => {
      if (isControlled) {
        onToggle?.(id)
        return
      }
      setInternalExpanded((prev) => {
        const next = new Set(prev)
        if (next.has(id)) next.delete(id)
        else next.add(id)
        return next
      })
    },
    [isControlled, onToggle],
  )

  function moveFocus(id: string) {
    setFocusedId(id)
    requestAnimationFrame(() => {
      const escaped = typeof CSS !== 'undefined' && CSS.escape ? CSS.escape(id) : id
      rootRef.current?.querySelector<HTMLElement>(`[data-tree-id="${escaped}"]`)?.focus()
    })
  }

  function select(id: string, type: TreeBrowserNodeType) {
    setFocusedId(id)
    setInternalSelected(id)
    onSelect?.(id, type)
  }

  function nodeType(el: Element): TreeBrowserNodeType {
    return el.getAttribute('data-type') === 'collection' ? 'collection' : 'item'
  }

  function handleFocus(e: React.FocusEvent<HTMLUListElement>) {
    const el = (e.target as HTMLElement).closest('[data-tree-id]')
    if (el) setFocusedId(el.getAttribute('data-tree-id') ?? focusedId)
  }

  function handleClick(e: React.MouseEvent<HTMLUListElement>) {
    const row = (e.target as HTMLElement).closest('.tree-browser__row')
    if (!row) return
    const el = row.closest('[data-tree-id]')
    if (!el) return
    const id = el.getAttribute('data-tree-id')
    if (!id) return
    const type = nodeType(el)
    select(id, type)
    if (type === 'collection' && hasChildren(collections, id)) toggle(id)
  }

  function handleKeyDown(e: KeyboardEvent<HTMLUListElement>) {
    const el = (e.target as HTMLElement).closest('[data-tree-id]')
    if (!el) return
    const id = el.getAttribute('data-tree-id')
    if (!id) return
    const type = nodeType(el)

    const flat = flattenVisible(collections, rootId, expandedSet)
    const idx = flat.findIndex((n) => n.id === id)
    const current = flat[idx]
    const nodeHasChildren = !!current?.hasChildren
    const isNodeExpanded = expandedSet.has(id)

    switch (e.key) {
      case 'ArrowDown': {
        e.preventDefault()
        const next = flat[idx + 1]
        if (next) moveFocus(next.id)
        break
      }
      case 'ArrowUp': {
        e.preventDefault()
        const prev = flat[idx - 1]
        if (prev) moveFocus(prev.id)
        break
      }
      case 'ArrowRight': {
        e.preventDefault()
        if (nodeHasChildren && !isNodeExpanded) toggle(id)
        else if (nodeHasChildren && isNodeExpanded) {
          const { collections: c, items: i } = childIds(collections, id)
          const first = c[0] ?? i[0]
          if (first) moveFocus(first)
        }
        break
      }
      case 'ArrowLeft': {
        e.preventDefault()
        if (nodeHasChildren && isNodeExpanded) toggle(id)
        else if (current?.parentId && current.parentId !== rootId) moveFocus(current.parentId)
        break
      }
      case 'Home': {
        e.preventDefault()
        if (flat[0]) moveFocus(flat[0].id)
        break
      }
      case 'End': {
        e.preventDefault()
        const last = flat[flat.length - 1]
        if (last) moveFocus(last.id)
        break
      }
      case 'Enter':
      case ' ': {
        e.preventDefault()
        select(id, type)
        if (type === 'collection' && nodeHasChildren) toggle(id)
        break
      }
    }
  }

  const rootChildren = childIds(collections, rootId)

  return (
    <ul
      ref={rootRef}
      role="tree"
      aria-label={label}
      data-variant={variant}
      className={`tree-browser ${className}`.trim()}
      onFocus={handleFocus}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      {...rest}
    >
      {rootChildren.collections.map((id) => (
        <TreeBrowserNode
          key={id}
          id={id}
          type="collection"
          collections={collections}
          items={items}
          expanded={expandedSet}
          selected={effectiveSelected}
          focusedId={focusedId}
          variant={variant}
          renderIcon={renderIcon}
          renderBadge={renderBadge}
        />
      ))}
      {rootChildren.items.map((id) => (
        <TreeBrowserNode
          key={id}
          id={id}
          type="item"
          collections={collections}
          items={items}
          expanded={expandedSet}
          selected={effectiveSelected}
          focusedId={focusedId}
          variant={variant}
          renderIcon={renderIcon}
          renderBadge={renderBadge}
        />
      ))}
    </ul>
  )
}

// packages/svelte/src/lib/components/TreeBrowser.svelte
<script module lang="ts">
  export type {
    TreeBrowserCollection,
    TreeBrowserItem,
    TreeBrowserData,
    TreeBrowserNodeType,
    FlatNode,
  } from './tree-browser-model.ts'
  export { topLevelIds } from './tree-browser-model.ts'
  export type { TreeBrowserRowContext } from './TreeBrowserNode.svelte'
</script>

<!--
  TreeBrowser - a folder/file tree modelled on instructure-ui's
  `ui-tree-browser` (TreeBrowser v2), medium size, `folderTree` variant.

  ## Data model
  instructure-ui shape: id-keyed `collections` (folders) + id-keyed
  `items` (leaves) + a `rootId`. The root collection is structural (its
  own row is never drawn); its `collections` then `items` become the
  top-level rows. Folders always render before items within a level.

  ## Visual mapping (instructure medium/folderTree -> @w5-ui/tokens)
  Both motifs (dark + light) resolve through the token variables below,
  so the component needs no motif branching.

  | instructure-ui (medium/folderTree) | @w5-ui token / utility            |
  | ---------------------------------- | --------------------------------- |
  | `baseSpacingMedium` row indent     | nested `ul` `pl-3` (12px = space-3)|
  | row min height                     | `min-h-8` (32px)                  |
  | row horizontal padding             | `px-2` (8px = space-2)            |
  | `iconsMarginRightMedium`           | `gap-2` (8px = space-2)           |
  | name font size (medium)            | `text-13` (--fs-13)               |
  | descriptor font size               | `text-11` (--fs-11), `text-text-4`|
  | folderTree `before` connector      | nested `ul` `border-l border-border-2` |
  | text colour (resting / selected)   | `text-text-2` / `text-text-1`     |
  | hover state                        | `bg-row-hover`                    |
  | selected state                     | `bg-brand-05/[0.18]`              |
  | focus ring                         | `--focus-ring` (`:focus-visible`) |

  ## Expansion
  Uncontrolled via `defaultExpanded`, or controlled via `expanded` +
  `ontoggle`. `topLevelIds(collections, rootId)` (exported) lets a
  consumer expand only the top level in one line.

  ## Accessibility
  `role="tree"` on the list, `role="treeitem"` / `role="group"` on rows
  and nested lists, `aria-expanded` / `aria-selected`, roving tabindex,
  and full Arrow/Home/End/Enter/Space keyboard navigation. Fixed row
  heights keep expansion CLS-free; the caret rotation respects
  `prefers-reduced-motion`.
-->
<script lang="ts">
  import { tick, type Snippet } from 'svelte'
  import TreeBrowserNode, { type TreeBrowserRowContext } from './TreeBrowserNode.svelte'
  import {
    childIds,
    flattenVisible,
    hasChildren,
    type TreeBrowserCollection,
    type TreeBrowserItem,
    type TreeBrowserNodeType,
  } from './tree-browser-model.ts'

  interface Props {
    collections?: Record<string, TreeBrowserCollection>;
    items?: Record<string, TreeBrowserItem>;
    rootId?: string;
    /** Uncontrolled initial expansion. Ignored when `expanded` is set. */
    defaultExpanded?: string[];
    /** Controlled expansion set. When provided, pair with `ontoggle`. */
    expanded?: string[] | undefined;
    ontoggle?: ((id: string) => void) | undefined;
    selected?: string | undefined;
    onselect?: ((id: string, type: TreeBrowserNodeType) => void) | undefined;
    /** Reserved for future small/large sizes. Only medium is implemented. */
    size?: 'medium';
    variant?: 'folderTree' | 'indent';
    label?: string | undefined;
    /** Per-row leading icon that overrides the built-in folder/file glyphs. */
    itemIcon?: Snippet<[TreeBrowserRowContext]>;
    /** Trailing badge (missing-file marker, count, etc.). */
    badge?: Snippet<[TreeBrowserRowContext]>;
    className?: string;
  }

  let {
    collections = {},
    items = {},
    rootId = 'root',
    defaultExpanded = [],
    expanded = undefined,
    ontoggle = undefined,
    selected = $bindable(undefined),
    onselect = undefined,
    size: _size = 'medium',
    variant = 'folderTree',
    label = undefined,
    itemIcon = undefined,
    badge = undefined,
    className = '',
  }: Props = $props()

  const isControlled = $derived(expanded !== undefined)

  // svelte-ignore state_referenced_locally
  let internalExpanded = $state(new Set<string>(defaultExpanded))
  let expandedSet = $derived(isControlled ? new Set(expanded) : internalExpanded)

  let data = $derived({ collections, items, rootId })
  let rootChildren = $derived(childIds(collections, rootId))
  let flat = $derived(flattenVisible(data, expandedSet))

  // svelte-ignore state_referenced_locally
  let focusedId = $state(flattenVisible({ collections, items, rootId }, new Set(defaultExpanded))[0]?.id ?? '')
  let rootEl = $state<HTMLUListElement | undefined>(undefined)

  function setExpanded(id: string, next: boolean) {
    if (isControlled) {
      ontoggle?.(id)
      return
    }
    if (next) internalExpanded.add(id)
    else internalExpanded.delete(id)
    internalExpanded = new Set(internalExpanded)
  }

  function toggle(id: string) {
    setExpanded(id, !expandedSet.has(id))
  }

  function select(id: string, type: TreeBrowserNodeType) {
    selected = id
    focusedId = id
    onselect?.(id, type)
  }

  async function moveFocus(id: string) {
    focusedId = id
    await tick()
    rootEl?.querySelector<HTMLElement>(`[data-tree-id="${cssEscape(id)}"]`)?.focus()
  }

  function cssEscape(value: string): string {
    return typeof CSS !== 'undefined' && CSS.escape ? CSS.escape(value) : value.replace(/"/g, '\\"')
  }

  function nodeType(el: Element): TreeBrowserNodeType {
    return el.getAttribute('data-type') === 'collection' ? 'collection' : 'item'
  }

  function handleFocusin(e: FocusEvent) {
    const el = (e.target as HTMLElement).closest('[data-tree-id]')
    if (el) focusedId = el.getAttribute('data-tree-id') ?? focusedId
  }

  function handleClick(e: MouseEvent) {
    const row = (e.target as HTMLElement).closest('.w5-tb__row')
    if (!row) return
    const el = row.closest('[data-tree-id]')
    if (!el) return
    const id = el.getAttribute('data-tree-id')
    if (!id) return
    const type = nodeType(el)
    select(id, type)
    if (type === 'collection' && hasChildren(collections, id)) toggle(id)
  }

  function handleKeydown(e: KeyboardEvent) {
    const el = (e.target as HTMLElement).closest('[data-tree-id]')
    if (!el) return
    const id = el.getAttribute('data-tree-id')
    if (!id) return
    const type = nodeType(el)

    const idx = flat.findIndex((n) => n.id === id)
    const current = flat[idx]
    const nodeHasChildren = !!current?.hasChildren
    const isNodeExpanded = expandedSet.has(id)

    switch (e.key) {
      case 'ArrowDown': {
        e.preventDefault()
        const next = flat[idx + 1]
        if (next) moveFocus(next.id)
        break
      }
      case 'ArrowUp': {
        e.preventDefault()
        const prev = flat[idx - 1]
        if (prev) moveFocus(prev.id)
        break
      }
      case 'ArrowRight': {
        e.preventDefault()
        if (nodeHasChildren && !isNodeExpanded) toggle(id)
        else if (nodeHasChildren && isNodeExpanded) {
          const first = firstChildId(id)
          if (first) moveFocus(first)
        }
        break
      }
      case 'ArrowLeft': {
        e.preventDefault()
        if (nodeHasChildren && isNodeExpanded) toggle(id)
        else if (current?.parentId && current.parentId !== rootId) moveFocus(current.parentId)
        break
      }
      case 'Home': {
        e.preventDefault()
        if (flat[0]) moveFocus(flat[0].id)
        break
      }
      case 'End': {
        e.preventDefault()
        const last = flat[flat.length - 1]
        if (last) moveFocus(last.id)
        break
      }
      case 'Enter':
      case ' ': {
        e.preventDefault()
        select(id, type)
        if (type === 'collection' && nodeHasChildren) toggle(id)
        break
      }
    }
  }

  function firstChildId(id: string): string | undefined {
    const { collections: c, items: i } = childIds(collections, id)
    return c[0] ?? i[0]
  }
</script>

<ul
  bind:this={rootEl}
  role="tree"
  aria-label={label}
  data-variant={variant}
  class={`w5-tb m-0 list-none p-0 text-text-2 ${className}`}
  onkeydown={handleKeydown}
  onfocusin={handleFocusin}
  onclick={handleClick}
>
  {#each rootChildren.collections as id (id)}
    <TreeBrowserNode
      {id}
      type="collection"
      {data}
      expanded={expandedSet}
      {selected}
      {focusedId}
      {variant}
      {itemIcon}
      {badge}
    />
  {/each}
  {#each rootChildren.items as id (id)}
    <TreeBrowserNode
      {id}
      type="item"
      {data}
      expanded={expandedSet}
      {selected}
      {focusedId}
      {variant}
      {itemIcon}
      {badge}
    />
  {/each}
</ul>

<style>
  .w5-tb :global([data-tree-id]:focus-visible > .w5-tb__row) {
    outline: var(--focus-ring);
    outline-offset: -2px;
  }
  .w5-tb :global([data-tree-id]:focus) {
    outline: none;
  }
</style>
