// packages/svelte/src/lib/components/AppLayout.svelte
<script lang="ts">
  import SkipLink from './SkipLink.svelte';

  interface Props {
    /** Page title for the visually-hidden h1 that labels main (WCAG 2.4.6). */
    pageLabel: string;
    class?: string;
    /** Topbar snippet, typically a Topbar component. */
    topbar?: import('svelte').Snippet;
    /** Sidebar snippet, typically a Sidebar component. */
    sidebar?: import('svelte').Snippet;
    children?: import('svelte').Snippet;
  }

  let {
    pageLabel,
    class: className = '',
    topbar,
    sidebar,
    children,
  }: Props = $props();
</script>

<div class="app {className}">
  <SkipLink />
  {@render topbar?.()}
  <div class="workspace">
    {@render sidebar?.()}
    <main class="content" id="main-content" tabindex="-1" aria-labelledby="page-title">
      <h1 id="page-title" class="sr-only">{pageLabel}</h1>
      {@render children?.()}
    </main>
  </div>
</div>

// packages/react/src/components/AppLayout.tsx
import type { ReactNode } from 'react'
import { SkipLink } from './SkipLink.js'

export interface AppLayoutProps {
  /** Rendered above the workspace, typically `<Topbar />`. */
  topbar: ReactNode
  /** Rendered to the left of the main content, typically `<Sidebar />`. */
  sidebar: ReactNode
  /** Page title for the visually-hidden `<h1>` that labels `<main>` (WCAG 2.4.6). */
  pageLabel: string
  children?: ReactNode
}

/**
 * Outer dashboard chrome: `<SkipLink>`, `<Topbar>` slot, `<Sidebar>` slot, and
 * a `<main className="content">` region with the page-title `<h1>` wired up.
 *
 * Reproducing this skeleton in userland is the #1 source of spacing drift —
 * `<AppLayout>` guarantees the `.app` grid, the `.workspace` columns, and the
 * sticky scroll container line up the same way the reference dashboards do.
 */
export function AppLayout({ topbar, sidebar, pageLabel, children }: AppLayoutProps) {
  return (
    <div className="app">
      <SkipLink />
      {topbar}
      <div className="workspace">
        {sidebar}
        <main className="content" id="main-content" tabIndex={-1} aria-labelledby="page-title">
          <h1 id="page-title" className="sr-only">
            {pageLabel}
          </h1>
          {children}
        </main>
      </div>
    </div>
  )
}
