// packages/svelte/src/lib/components/Avatar.svelte
<script module lang="ts">
  export type AvatarSize = 'sm' | 'md' | 'lg';
  export type AvatarStatus = 'online' | 'offline' | 'away';
</script>

<script lang="ts">
  interface Props {
    initials?: string;
    src?: string | undefined;
    alt?: string | undefined;
    size?: AvatarSize;
    status?: AvatarStatus | undefined;
    className?: string;
    style?: string;
  }

  let {
    initials = '?',
    src = undefined,
    alt = undefined,
    size = 'md',
    status = undefined,
    className = '',
    style = ''
  }: Props = $props();
</script>

<span
  class="avatar avatar-{size}{className ? ` ${className}` : ''}"
  role="img"
  aria-label={alt ?? (src ? '' : initials)}
  {style}
>
  {#if src}
    <img {src} alt="" />
  {:else}
    {initials}
  {/if}
  {#if status}
    <span class="avatar-status avatar-status-{status}" aria-hidden="true"></span>
  {/if}
</span>

// packages/react/src/components/Avatar.tsx
import type { CSSProperties } from 'react';

export type AvatarSize = 'sm' | 'md' | 'lg';
export type AvatarStatus = 'online' | 'offline' | 'away';

export interface AvatarProps {
  initials?: string;
  src?: string;
  alt?: string;
  size?: AvatarSize;
  status?: AvatarStatus;
  className?: string;
  style?: CSSProperties;
}

export function Avatar({
  initials = '?',
  src,
  alt,
  size = 'md',
  status,
  className = '',
  style,
}: AvatarProps) {
  const label = alt ?? (src ? '' : initials);
  return (
    <span
      className={`avatar avatar-${size}${className ? ` ${className}` : ''}`}
      role="img"
      aria-label={label}
      style={style}
    >
      {src ? <img src={src} alt="" /> : initials}
      {status && <span className={`avatar-status avatar-status-${status}`} aria-hidden="true" />}
    </span>
  );
}
