// packages/svelte/src/lib/components/ContextMenu.svelte
<script lang="ts" module>
  export interface ContextMenuItem {
    id: string;
    label: string;
    danger?: boolean;
    disabled?: boolean;
  }
  export type ContextMenuEntry = ContextMenuItem | { separator: true };
</script>

<script lang="ts">
  import { onDestroy, tick, createEventDispatcher } from 'svelte';

  interface Props {
    items?: ContextMenuEntry[];
    x?: number;
    y?: number;
    open?: boolean;
    label?: string;
  }

  let {
    items = [],
    x = 0,
    y = 0,
    open = false,
    label = 'Context menu'
  }: Props = $props();

  const dispatch = createEventDispatcher<{ close: void; action: string }>();

  let menuEl: HTMLUListElement = $state();
  let activeIdx = $state(0);

  let actionItems = $derived(items.reduce<ContextMenuItem[]>((acc, e) => {
    if (!('separator' in e)) acc.push(e);
    return acc;
  }, []));

  const menuW = 168;
  let menuH = $derived(items.length * 30 + 8);
  let cx = $derived(Math.min(x, (typeof window !== 'undefined' ? window.innerWidth : 1200) - menuW - 8));
  let cy = $derived(Math.min(y, (typeof window !== 'undefined' ? window.innerHeight : 800) - menuH - 8));

  function activate(id: string) {
    dispatch('action', id);
    dispatch('close');
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape') { e.preventDefault(); dispatch('close'); }
    else if (e.key === 'ArrowDown') { e.preventDefault(); activeIdx = Math.min(activeIdx + 1, actionItems.length - 1); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); activeIdx = Math.max(activeIdx - 1, 0); }
    else if (e.key === 'Home') { e.preventDefault(); activeIdx = 0; }
    else if (e.key === 'End') { e.preventDefault(); activeIdx = actionItems.length - 1; }
    else if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      const item = actionItems[activeIdx];
      if (item && !item.disabled) activate(item.id);
    }
    else if (e.key === 'Tab') { dispatch('close'); }
  }

  function handleOutside(e: MouseEvent) {
    if (!menuEl?.contains(e.target as Node)) dispatch('close');
  }

  $effect(() => {
    if (open) {
      activeIdx = 0;
      tick().then(() => menuEl?.focus());
      document.addEventListener('mousedown', handleOutside);
    } else {
      document.removeEventListener('mousedown', handleOutside);
    }
  });

  onDestroy(() => {
    document.removeEventListener('mousedown', handleOutside);
  });

  function actionIndex(entry: ContextMenuEntry): number {
    if ('separator' in entry) return -1;
    return actionItems.indexOf(entry as ContextMenuItem);
  }
</script>

{#if open}
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
  <ul
    bind:this={menuEl}
    role="menu"
    aria-label={label}
    tabindex="-1"
    class="ctx-menu"
    style="left:{cx}px;top:{cy}px"
    onkeydown={handleKeyDown}
  >
    {#each items as entry, i (i)}
      {#if 'separator' in entry}
        <li role="separator" class="ctx-menu-sep"></li>
      {:else}
        <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
        <li
          role="menuitem"
          tabindex="-1"
          aria-disabled={entry.disabled || undefined}
          data-active={actionIndex(entry) === activeIdx ? 'true' : undefined}
          data-danger={entry.danger || undefined}
          class="ctx-menu-item"
          onmouseenter={() => (activeIdx = actionIndex(entry))}
          onmousedown={(e) => { e.preventDefault(); (() => { if (!entry.disabled) activate(entry.id); })(e); }}
        >
          {entry.label}
        </li>
      {/if}
    {/each}
  </ul>
{/if}

// packages/react/src/components/ContextMenu.tsx
import { useState, useRef, useEffect, useId } from 'react'
import type { KeyboardEvent } from 'react'

export interface ContextMenuItem {
  id: string
  label: string
  danger?: boolean
  disabled?: boolean
}

export type ContextMenuEntry = ContextMenuItem | { separator: true }

export interface ContextMenuProps {
  items: ContextMenuEntry[]
  x: number
  y: number
  open: boolean
  onClose: () => void
  onAction: (id: string) => void
  label?: string
}

export function ContextMenu({
  items,
  x,
  y,
  open,
  onClose,
  onAction,
  label = 'Context menu',
}: ContextMenuProps) {
  const uid = useId()
  const menuId = `${uid}-ctxmenu`
  const [activeIdx, setActiveIdx] = useState(0)
  const menuRef = useRef<HTMLUListElement>(null)

  const actionItems = items.reduce<ContextMenuItem[]>((acc, e) => {
    if (!('separator' in e)) acc.push(e)
    return acc
  }, [])

  useEffect(() => {
    if (!open) return
    setActiveIdx(0)
    requestAnimationFrame(() => menuRef.current?.focus())
    function handler(e: MouseEvent) {
      if (!menuRef.current?.contains(e.target as Node)) onClose()
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [open, onClose])

  function activate(id: string) {
    onAction(id)
    onClose()
  }

  function onKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      e.preventDefault()
      onClose()
    } else if (e.key === 'ArrowDown') {
      e.preventDefault()
      setActiveIdx((i) => Math.min(i + 1, actionItems.length - 1))
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      setActiveIdx((i) => Math.max(i - 1, 0))
    } else if (e.key === 'Home') {
      e.preventDefault()
      setActiveIdx(0)
    } else if (e.key === 'End') {
      e.preventDefault()
      setActiveIdx(actionItems.length - 1)
    } else if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault()
      const item = actionItems[activeIdx]
      if (item && !item.disabled) activate(item.id)
    } else if (e.key === 'Tab') {
      onClose()
    }
  }

  if (!open) return null

  const menuW = 168
  const menuH = items.length * 30 + 8
  const cx = Math.min(x, window.innerWidth - menuW - 8)
  const cy = Math.min(y, window.innerHeight - menuH - 8)

  return (
    <ul
      ref={menuRef}
      id={menuId}
      role="menu"
      aria-label={label}
      tabIndex={-1}
      className="ctx-menu"
      style={{ left: cx, top: cy }}
      onKeyDown={onKeyDown}
    >
      {items.map((entry, i) => {
        if ('separator' in entry) {
          return <li key={i} role="separator" className="ctx-menu-sep" />
        }
        const ai = actionItems.indexOf(entry)
        return (
          <li
            key={entry.id}
            role="menuitem"
            tabIndex={-1}
            aria-disabled={entry.disabled || undefined}
            data-active={ai === activeIdx ? 'true' : undefined}
            data-danger={entry.danger || undefined}
            className="ctx-menu-item"
            onMouseEnter={() => setActiveIdx(ai)}
            onMouseDown={(e) => {
              e.preventDefault()
              if (!entry.disabled) activate(entry.id)
            }}
          >
            {entry.label}
          </li>
        )
      })}
    </ul>
  )
}
