// packages/svelte/src/lib/components/Drawer.svelte
<script lang="ts">
  import { tick } from 'svelte';
  import IconButton from './IconButton.svelte';
  import CloseIcon from '../icons/CloseIcon.svelte';
  export let open: boolean = false;
  export let title: string;
  const titleId = `drawer-title-${Math.random().toString(36).slice(2, 9)}`;
  const FOCUSABLE =
    'a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
  let panelEl: HTMLDivElement;
  let prev: HTMLElement | null = null;
  let wasOpen = false;
  $: if (open && !wasOpen) {
    prev = typeof document !== 'undefined' ? (document.activeElement as HTMLElement | null) : null;
    wasOpen = true;
    tick().then(() => {
      const first = panelEl?.querySelector<HTMLElement>(FOCUSABLE);
      (first ?? panelEl)?.focus();
    });
  } else if (!open && wasOpen) {
    wasOpen = false;
    prev?.focus?.();
  }
  function onKeydown(e: KeyboardEvent) {
    if (!open) return;
    if (e.key === 'Escape') { open = false; return; }
    if (e.key !== 'Tab' || !panelEl) return;
    const items = Array.from(panelEl.querySelectorAll<HTMLElement>(FOCUSABLE));
    if (!items.length) { e.preventDefault(); return; }
    const f = items[0]!, l = items[items.length - 1]!;
    const active = document.activeElement;
    if (e.shiftKey && active === f) { e.preventDefault(); l.focus(); }
    else if (!e.shiftKey && active === l) { e.preventDefault(); f.focus(); }
  }
</script>

<svelte:window on:keydown={onKeydown} />

<div
  class="drawer-overlay {open ? 'show' : ''}"
  on:click={() => (open = false)}
  aria-hidden="true"
  role="presentation"
/>
<div
  bind:this={panelEl}
  class="drawer-panel {open ? 'show' : ''}"
  role="dialog"
  aria-modal="true"
  aria-labelledby={titleId}
  tabindex="-1"
>
  <div class="drawer-h">
    <h2 id={titleId}>{title}</h2>
    <IconButton title="Close" on:click={() => (open = false)}>
      <CloseIcon />
    </IconButton>
  </div>
  <div class="drawer-b"><slot /></div>
</div>

// packages/react/src/components/Drawer.tsx
import { useEffect, useId, useRef, type ReactNode } from 'react';
import { IconButton } from './Button.js';
import { CloseIcon } from '../icons.js';

export interface DrawerProps {
  open: boolean;
  title: string;
  onClose: () => void;
  children?: ReactNode;
}

const FOCUSABLE =
  'a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';

export function Drawer({ open, title, onClose, children }: DrawerProps) {
  const titleId = useId();
  const panelRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const prev = document.activeElement as HTMLElement | null;
    const panel = panelRef.current;
    const first = panel?.querySelector<HTMLElement>(FOCUSABLE);
    (first ?? panel)?.focus();

    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') { onClose(); return; }
      if (e.key !== 'Tab' || !panel) return;
      const items = Array.from(panel.querySelectorAll<HTMLElement>(FOCUSABLE));
      if (!items.length) { e.preventDefault(); return; }
      const f = items[0]!, l = items[items.length - 1]!;
      const active = document.activeElement;
      if (e.shiftKey && active === f) { e.preventDefault(); l.focus(); }
      else if (!e.shiftKey && active === l) { e.preventDefault(); f.focus(); }
    }

    window.addEventListener('keydown', onKey);
    return () => { window.removeEventListener('keydown', onKey); prev?.focus?.(); };
  }, [open, onClose]);

  return (
    <>
      <div
        className={`drawer-overlay ${open ? 'show' : ''}`}
        onClick={onClose}
        aria-hidden="true"
      />
      <div
        ref={panelRef}
        className={`drawer-panel ${open ? 'show' : ''}`}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        tabIndex={-1}
      >
        <div className="drawer-h">
          <h2 id={titleId}>{title}</h2>
          <IconButton onClick={onClose} aria-label="Close">
            <CloseIcon />
          </IconButton>
        </div>
        <div className="drawer-b">{children}</div>
      </div>
    </>
  );
}
