// packages/svelte/src/lib/components/FieldStack.svelte
<script lang="ts">
  interface Props {
    class?: string;
    children?: import('svelte').Snippet;
  }

  let { class: className = '', children }: Props = $props();
</script>

<!--
  Single-column form rhythm: a vertical stack of <Field>s with the canonical
  16px gap. Typed equivalent of `<div class="field-stack">` from
  @w5-ui/tokens/dashboard.css. Reach for this inside narrow <Card> tiles and
  <Modal> bodies.
-->
<div class="field-stack {className}">
  {@render children?.()}
</div>

// packages/react/src/components/FieldStack.tsx
import type { HTMLAttributes, ReactNode } from 'react'

export interface FieldStackProps extends HTMLAttributes<HTMLDivElement> {
  children?: ReactNode
}

/**
 * Single-column form rhythm: a vertical stack of `<Field>`s with the canonical
 * 16 px gap. Typed equivalent of `<div className="field-stack">` from
 * `@w5-ui/tokens/dashboard.css`. Reach for this inside narrow `<Card>` tiles
 * and `<Modal>` bodies.
 */
export function FieldStack({ className = '', children, ...rest }: FieldStackProps) {
  return (
    <div className={`field-stack ${className}`.trim()} {...rest}>
      {children}
    </div>
  )
}
