// packages/svelte/src/lib/components/FormRow.svelte
<script lang="ts">
  interface Props {
    class?: string;
    children?: import('svelte').Snippet;
  }

  let { class: className = '', children }: Props = $props();
</script>

<!--
  Two-column form grid (1fr 1fr, 14px gap, 6px top offset) that every Settings
  card uses. Typed equivalent of `<div class="form-row">` from
  @w5-ui/tokens/dashboard.css. Use inside wider <Card> tiles for dense editors.
-->
<div class="form-row {className}">
  {@render children?.()}
</div>

// packages/react/src/components/FormRow.tsx
import type { HTMLAttributes, ReactNode } from 'react'

export interface FormRowProps extends HTMLAttributes<HTMLDivElement> {
  children?: ReactNode
}

/**
 * Two-column form grid: `1fr 1fr` with the canonical 14 px gap and 6 px top
 * offset that every Settings card uses. Typed equivalent of
 * `<div className="form-row">` from `@w5-ui/tokens/dashboard.css`. Use inside
 * wider `<Card>` tiles for dense editors.
 */
export function FormRow({ className = '', children, ...rest }: FormRowProps) {
  return (
    <div className={`form-row ${className}`.trim()} {...rest}>
      {children}
    </div>
  )
}
