// packages/svelte/src/lib/components/HoverCard.svelte
<script module lang="ts">
  let counter = 0;
</script>

<script lang="ts">
  import { onDestroy } from 'svelte';
  interface Props {
    placement?: 'top' | 'bottom' | 'left' | 'right';
    delay?: number;
    class?: string;
    trigger?: import('svelte').Snippet;
    content?: import('svelte').Snippet;
  }

  let {
    placement = 'bottom',
    delay = 300,
    class: className = '',
    trigger,
    content
  }: Props = $props();
  

  const id = `dash-ui-hovercard-${++counter}`;
  let open = $state(false);
  let timer: ReturnType<typeof setTimeout> | null = null;

  function show() {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => { open = true; }, delay);
  }

  function hide() {
    if (timer) clearTimeout(timer);
    open = false;
  }

  onDestroy(() => { if (timer) clearTimeout(timer); });
</script>

<div
  role="group"
  class="hovercard-wrapper hovercard-{placement} {className}"
  onmouseenter={show}
  onmouseleave={hide}
  onfocusin={show}
  onfocusout={hide}
>
  <div class="hovercard-trigger" aria-describedby={open ? id : undefined}>
    {@render trigger?.()}
  </div>
  {#if open}
    <div {id} role="tooltip" class="hovercard">
      {@render content?.()}
    </div>
  {/if}
</div>

// packages/react/src/components/HoverCard.tsx
import { useId, useRef, useState, type ReactNode } from 'react'

export type HoverCardPlacement = 'top' | 'bottom' | 'left' | 'right'

export interface HoverCardProps {
  content: ReactNode
  children: ReactNode
  placement?: HoverCardPlacement
  delay?: number
  className?: string
}

export function HoverCard({
  content,
  children,
  placement = 'bottom',
  delay = 300,
  className = '',
}: HoverCardProps) {
  const id = useId()
  const [open, setOpen] = useState(false)
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null)

  function show() {
    if (timer.current) clearTimeout(timer.current)
    timer.current = setTimeout(() => setOpen(true), delay)
  }

  function hide() {
    if (timer.current) clearTimeout(timer.current)
    setOpen(false)
  }

  return (
    <div
      className={`hovercard-wrapper hovercard-${placement} ${className}`.trim()}
      onMouseEnter={show}
      onMouseLeave={hide}
      onFocus={show}
      onBlur={hide}
    >
      <div className="hovercard-trigger" aria-describedby={open ? id : undefined}>
        {children}
      </div>
      {open && (
        <div id={id} role="tooltip" className="hovercard">
          {content}
        </div>
      )}
    </div>
  )
}
