// packages/svelte/src/lib/components/InputGroup.svelte
<script lang="ts">
  export let prefix: string | undefined = undefined;
  export let suffix: string | undefined = undefined;
</script>

<div class="input-group">
  {#if prefix !== undefined}
    <span class="input-group-addon input-group-addon--prefix">{prefix}</span>
  {/if}
  <slot />
  {#if suffix !== undefined}
    <span class="input-group-addon input-group-addon--suffix">{suffix}</span>
  {/if}
</div>

// packages/react/src/components/InputGroup.tsx
import type { ReactNode } from 'react';

export interface InputGroupProps {
  prefix?: ReactNode;
  suffix?: ReactNode;
  children: ReactNode;
}

export function InputGroup({ prefix, suffix, children }: InputGroupProps) {
  return (
    <div className="input-group">
      {prefix !== undefined && (
        <span className="input-group-addon input-group-addon--prefix">{prefix}</span>
      )}
      {children}
      {suffix !== undefined && (
        <span className="input-group-addon input-group-addon--suffix">{suffix}</span>
      )}
    </div>
  );
}
