// packages/wc/src/elements/InputGroup.wc.svelte
<svelte:options customElement={{ tag: "uni-input-group", extend: withShadowStyles }} />
<script>
  import Original from '@w5-ui/svelte/components/InputGroup.svelte';
  import { withShadowStyles } from '../styled.ts';
  let {
    prefix = undefined,
    suffix = undefined
  } = $props();
</script>

<Original {prefix} {suffix}>
  <slot />
</Original>

// packages/react/src/components/InputGroup.tsx
import type { ReactNode } from 'react';

export interface InputGroupProps {
  prefix?: ReactNode;
  suffix?: ReactNode;
  children: ReactNode;
}

export function InputGroup({ prefix, suffix, children }: InputGroupProps) {
  return (
    <div className="input-group">
      {prefix !== undefined && (
        <span className="input-group-addon input-group-addon--prefix">{prefix}</span>
      )}
      {children}
      {suffix !== undefined && (
        <span className="input-group-addon input-group-addon--suffix">{suffix}</span>
      )}
    </div>
  );
}
