// packages/svelte/src/lib/components/Kbd.svelte
<script lang="ts">
  export let keys: string | string[];
  let className = '';
  export { className as class };

  $: parts = typeof keys === 'string' ? keys.split('+') : keys;
</script>

<kbd class="kbd {className}">
  {#each parts as key, i}
    <span class="kbd__segment">
      {#if i > 0}<span class="kbd__plus" aria-hidden="true">+</span>{/if}
      <kbd class="kbd__key">{key}</kbd>
    </span>
  {/each}
</kbd>

// packages/react/src/components/Kbd.tsx
export interface KbdProps {
  keys: string | string[]
  className?: string
}

export function Kbd({ keys, className = '' }: KbdProps) {
  const parts = typeof keys === 'string' ? keys.split('+') : keys
  return (
    <kbd className={`kbd ${className}`.trim()}>
      {parts.map((k, i) => (
        <span key={i} className="kbd__segment">
          {i > 0 && (
            <span className="kbd__plus" aria-hidden="true">
              +
            </span>
          )}
          <kbd className="kbd__key">{k}</kbd>
        </span>
      ))}
    </kbd>
  )
}
