// packages/svelte/src/lib/components/Modal.svelte
<script lang="ts">
  import { tick } from 'svelte';
  import IconButton from './IconButton.svelte';
  import CloseIcon from '../icons/CloseIcon.svelte';
  interface Props {
    open?: boolean;
    title: string;
    children?: import('svelte').Snippet;
    footer?: import('svelte').Snippet;
  }

  let {
    open = $bindable(false),
    title,
    children,
    footer
  }: Props = $props();
  const titleId = `modal-title-${Math.random().toString(36).slice(2, 9)}`;
  const FOCUSABLE =
    'a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
  let modalEl: HTMLDivElement = $state();
  let previouslyFocused: HTMLElement | null = $state(null);
  let prevOverflow = $state('');
  let wasOpen = $state(false);
  let downOnBackdrop = $state(false);
  $effect(() => {
    if (open && !wasOpen) {
      previouslyFocused = (typeof document !== 'undefined'
        ? (document.activeElement as HTMLElement | null)
        : null);
      if (typeof document !== 'undefined') {
        prevOverflow = document.body.style.overflow;
        document.body.style.overflow = 'hidden';
      }
      wasOpen = true;
      tick().then(() => {
        const first = modalEl?.querySelector<HTMLElement>(FOCUSABLE);
        (first ?? modalEl)?.focus();
      });
    } else if (!open && wasOpen) {
      wasOpen = false;
      if (typeof document !== 'undefined') {
        document.body.style.overflow = prevOverflow;
      }
      previouslyFocused?.focus?.();
    }
  });
  function onKeydown(e: KeyboardEvent) {
    if (!open) return;
    if (e.key === 'Escape') {
      open = false;
      return;
    }
    if (e.key !== 'Tab' || !modalEl) return;
    const items = Array.from(modalEl.querySelectorAll<HTMLElement>(FOCUSABLE));
    if (items.length === 0) {
      e.preventDefault();
      return;
    }
    const f = items[0]!;
    const l = items[items.length - 1]!;
    const active = document.activeElement;
    if (e.shiftKey && active === f) {
      e.preventDefault();
      l.focus();
    } else if (!e.shiftKey && active === l) {
      e.preventDefault();
      f.focus();
    }
  }
</script>

<svelte:window onkeydown={onKeydown} />

<div
  class="backdrop {open ? 'show' : ''}"
  onmousedown={(e) => (downOnBackdrop = e.target === e.currentTarget)}
  onclick={(e) => {
    if (downOnBackdrop && e.target === e.currentTarget) open = false;
    downOnBackdrop = false;
  }}
  role="presentation"
>
  <div
    bind:this={modalEl}
    class="modal"
    role="dialog"
    aria-modal="true"
    aria-labelledby={titleId}
    tabindex="-1"
  >
    <div class="modal-h">
      <h2 id={titleId}>{title}</h2>
      <IconButton title="Close" on:click={() => (open = false)}>
        <CloseIcon />
      </IconButton>
    </div>
    <div class="modal-b">{@render children?.()}</div>
    {#if footer}
      <div class="modal-f">{@render footer?.()}</div>
    {/if}
  </div>
</div>

// packages/react/src/components/Modal.tsx
import { useEffect, useId, useRef, type ReactNode } from 'react'
import { CloseIcon } from '../icons.js'
import { IconButton } from './Button.js'

export interface ModalProps {
  open: boolean
  title: string
  onClose: () => void
  children?: ReactNode
  footer?: ReactNode
}

const FOCUSABLE =
  'a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])'

export function Modal({ open, title, onClose, children, footer }: ModalProps) {
  const titleId = useId()
  const modalRef = useRef<HTMLDivElement>(null)
  const downOnBackdropRef = useRef(false)
  useEffect(() => {
    if (!open) return
    const previouslyFocused = document.activeElement as HTMLElement | null
    const prevOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    const node = modalRef.current
    const first = node?.querySelector<HTMLElement>(FOCUSABLE)
    ;(first ?? node)?.focus()
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose()
        return
      }
      if (e.key !== 'Tab' || !node) return
      const items = Array.from(node.querySelectorAll<HTMLElement>(FOCUSABLE))
      if (items.length === 0) {
        e.preventDefault()
        return
      }
      const f = items[0]!
      const l = items[items.length - 1]!
      const active = document.activeElement
      if (e.shiftKey && active === f) {
        e.preventDefault()
        l.focus()
      } else if (!e.shiftKey && active === l) {
        e.preventDefault()
        f.focus()
      }
    }
    window.addEventListener('keydown', onKey)
    return () => {
      window.removeEventListener('keydown', onKey)
      document.body.style.overflow = prevOverflow
      previouslyFocused?.focus?.()
    }
  }, [open, onClose])
  return (
    <div
      className={`backdrop ${open ? 'show' : ''}`}
      onMouseDown={(e) => {
        downOnBackdropRef.current = e.target === e.currentTarget
      }}
      onClick={(e) => {
        if (downOnBackdropRef.current && e.target === e.currentTarget) onClose()
        downOnBackdropRef.current = false
      }}
    >
      <div
        ref={modalRef}
        className="modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        tabIndex={-1}
      >
        <div className="modal-h">
          <h2 id={titleId}>{title}</h2>
          <IconButton onClick={onClose} aria-label="Close">
            <CloseIcon />
          </IconButton>
        </div>
        <div className="modal-b">{children}</div>
        {footer && <div className="modal-f">{footer}</div>}
      </div>
    </div>
  )
}
