// packages/svelte/src/lib/components/ProgressBar.svelte
<script lang="ts">
  export let value: number;
  export let label: string | undefined = undefined;
  export let valueText: string | undefined = undefined;
  export let color: string = '#006FFF';
  $: clamped = Math.max(0, Math.min(100, value));
  $: displayed = valueText ?? `${Math.round(clamped)}%`;
  $: hasHeader = label !== undefined || valueText !== undefined;
</script>

<div class="pb">
  {#if hasHeader}
    <div class="pb-header">
      {#if label}<span class="pb-label">{label}</span>{/if}
      <span class="pb-value">{displayed}</span>
    </div>
  {/if}
  <div
    class="pb-track"
    role="progressbar"
    aria-valuenow={Math.round(clamped)}
    aria-valuemin={0}
    aria-valuemax={100}
    aria-label={label}
    aria-valuetext={displayed}
  >
    <div class="pb-fill" style="width:{clamped}%;background:{color};" />
  </div>
</div>

// packages/react/src/components/ProgressBar.tsx
export interface ProgressBarProps {
  value: number;
  label?: string;
  valueText?: string;
  color?: string;
}

export function ProgressBar({ value, label, valueText, color = '#006FFF' }: ProgressBarProps) {
  const clamped = Math.max(0, Math.min(100, value));
  const displayed = valueText ?? `${Math.round(clamped)}%`;
  const hasHeader = label !== undefined || valueText !== undefined;
  return (
    <div className="pb">
      {hasHeader && (
        <div className="pb-header">
          {label && <span className="pb-label">{label}</span>}
          <span className="pb-value">{displayed}</span>
        </div>
      )}
      <div
        className="pb-track"
        role="progressbar"
        aria-valuenow={Math.round(clamped)}
        aria-valuemin={0}
        aria-valuemax={100}
        aria-label={label}
        aria-valuetext={displayed}
      >
        <div className="pb-fill" style={{ width: `${clamped}%`, background: color }} />
      </div>
    </div>
  );
}
