// packages/svelte/src/lib/components/RadioGroup.svelte
<script module lang="ts">
  let counter = 0;
  export interface RadioOption {
    value: string;
    label: string;
    description?: string;
    disabled?: boolean;
  }
</script>

<script lang="ts">
  interface Props {
    legend: string;
    name?: string | undefined;
    options?: RadioOption[];
    value?: string | undefined;
    srOnlyLegend?: boolean;
    horizontal?: boolean;
  }

  let {
    legend,
    name = undefined,
    options = [],
    value = $bindable(undefined),
    srOnlyLegend = false,
    horizontal = false
  }: Props = $props();

  const groupName = name ?? `dash-ui-rg-${++counter}`;
</script>

<fieldset class="radio-group {horizontal ? 'radio-group--h' : ''}">
  <legend class={srOnlyLegend ? 'sr-only' : 'radio-group__legend'}>{legend}</legend>
  {#each options as opt}
    {@const optId = `${groupName}-${opt.value}`}
    <label
      for={optId}
      class="radio-option{opt.disabled ? ' radio-option--disabled' : ''}"
    >
      <input
        type="radio"
        id={optId}
        name={groupName}
        value={opt.value}
        checked={value === opt.value}
        disabled={opt.disabled}
        class="radio"
        onchange={() => { value = opt.value; }}
      />
      <span class="radio-text">
        <span>{opt.label}</span>
        {#if opt.description}
          <span class="radio-description">{opt.description}</span>
        {/if}
      </span>
    </label>
  {/each}
</fieldset>

// packages/react/src/components/RadioGroup.tsx
import { useId } from 'react';
import type { ReactNode } from 'react';

export interface RadioOption {
  value: string;
  label: ReactNode;
  description?: string;
  disabled?: boolean;
}

export interface RadioGroupProps {
  legend: string;
  name?: string;
  options: RadioOption[];
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  srOnlyLegend?: boolean;
  horizontal?: boolean;
}

export function RadioGroup({
  legend,
  name,
  options,
  value,
  defaultValue,
  onChange,
  srOnlyLegend = false,
  horizontal = false,
}: RadioGroupProps) {
  const groupId = useId();
  const groupName = name ?? groupId;
  const cls = ['radio-group', horizontal && 'radio-group--h'].filter(Boolean).join(' ');

  return (
    <fieldset className={cls}>
      <legend className={srOnlyLegend ? 'sr-only' : 'radio-group__legend'}>{legend}</legend>
      {options.map((opt) => {
        const optId = `${groupName}-${opt.value}`;
        return (
          <label
            key={opt.value}
            htmlFor={optId}
            className={['radio-option', opt.disabled && 'radio-option--disabled'].filter(Boolean).join(' ')}
          >
            <input
              type="radio"
              id={optId}
              name={groupName}
              value={opt.value}
              checked={value !== undefined ? value === opt.value : undefined}
              defaultChecked={defaultValue !== undefined ? defaultValue === opt.value : undefined}
              disabled={opt.disabled}
              onChange={() => onChange?.(opt.value)}
              className="radio"
            />
            <span className="radio-text">
              <span>{opt.label}</span>
              {opt.description && <span className="radio-description">{opt.description}</span>}
            </span>
          </label>
        );
      })}
    </fieldset>
  );
}
