// packages/svelte/src/lib/components/ResizablePanel.svelte
<script module lang="ts">
  export type ResizableOrientation = 'horizontal' | 'vertical';
</script>

<script lang="ts">
  interface Props {
    defaultSize?: number;
    min?: number;
    max?: number;
    orientation?: ResizableOrientation;
    label?: string;
    style?: string;
    first?: import('svelte').Snippet;
    second?: import('svelte').Snippet;
  }

  let {
    defaultSize = 50,
    min = 20,
    max = 80,
    orientation = 'vertical',
    label = 'Resize panels',
    style = '',
    first,
    second
  }: Props = $props();

  let size = $state(defaultSize);
  let container: HTMLDivElement = $state();

  function clamp(v: number) { return Math.min(max, Math.max(min, v)); }

  function onMouseDown(e: MouseEvent) {
    e.preventDefault();

    function onMove(me: MouseEvent) {
      if (!container) return;
      const rect = container.getBoundingClientRect();
      const pct = orientation === 'vertical'
        ? ((me.clientX - rect.left) / rect.width) * 100
        : ((me.clientY - rect.top) / rect.height) * 100;
      size = clamp(Math.round(pct));
    }

    function onUp() {
      window.removeEventListener('mousemove', onMove);
      window.removeEventListener('mouseup', onUp);
    }

    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
  }

  function onKeyDown(e: KeyboardEvent) {
    const step = e.shiftKey ? 10 : 1;
    if (orientation === 'vertical') {
      if (e.key === 'ArrowLeft') { e.preventDefault(); size = clamp(size - step); }
      if (e.key === 'ArrowRight') { e.preventDefault(); size = clamp(size + step); }
    } else {
      if (e.key === 'ArrowUp') { e.preventDefault(); size = clamp(size - step); }
      if (e.key === 'ArrowDown') { e.preventDefault(); size = clamp(size + step); }
    }
    if (e.key === 'Home') { e.preventDefault(); size = min; }
    if (e.key === 'End') { e.preventDefault(); size = max; }
  }

  let firstStyle = $derived(orientation === 'vertical'
    ? `flex: 0 0 ${size}%; min-width: 0;`
    : `flex: 0 0 ${size}%; min-height: 0;`);
</script>

<div bind:this={container} class="rp rp--{orientation}" {style}>
  <div class="rp-pane" style={firstStyle}>
    {@render first?.()}
  </div>
  <!-- svelte-ignore a11y_no_noninteractive_tabindex, a11y_no_noninteractive_element_interactions -->
  <div
    role="separator"
    tabindex="0"
    aria-orientation={orientation}
    aria-valuenow={size}
    aria-valuemin={min}
    aria-valuemax={max}
    aria-label={label}
    class="rp-handle"
    onmousedown={onMouseDown}
    onkeydown={onKeyDown}
></div>
  <div class="rp-pane rp-pane--second">
    {@render second?.()}
  </div>
</div>

// packages/react/src/components/ResizablePanel.tsx
import { useRef, useState, useCallback, type ReactNode, type CSSProperties } from 'react'

export type ResizableOrientation = 'horizontal' | 'vertical'

export interface ResizablePanelProps {
  defaultSize?: number
  min?: number
  max?: number
  orientation?: ResizableOrientation
  label?: string
  className?: string
  style?: CSSProperties
  children: [ReactNode, ReactNode]
}

export function ResizablePanel({
  defaultSize = 50,
  min = 20,
  max = 80,
  orientation = 'vertical',
  label = 'Resize panels',
  className,
  style,
  children,
}: ResizablePanelProps) {
  const [size, setSize] = useState(defaultSize)
  const containerRef = useRef<HTMLDivElement>(null)
  const dragging = useRef(false)

  const clamp = useCallback((v: number) => Math.min(max, Math.max(min, v)), [min, max])

  const onMouseDown = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault()
      dragging.current = true

      const onMove = (me: MouseEvent) => {
        if (!dragging.current || !containerRef.current) return
        const rect = containerRef.current.getBoundingClientRect()
        const pct =
          orientation === 'vertical'
            ? ((me.clientX - rect.left) / rect.width) * 100
            : ((me.clientY - rect.top) / rect.height) * 100
        setSize(clamp(Math.round(pct)))
      }

      const onUp = () => {
        dragging.current = false
        window.removeEventListener('mousemove', onMove)
        window.removeEventListener('mouseup', onUp)
      }

      window.addEventListener('mousemove', onMove)
      window.addEventListener('mouseup', onUp)
    },
    [orientation, clamp],
  )

  const onKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      const step = e.shiftKey ? 10 : 1
      if (orientation === 'vertical') {
        if (e.key === 'ArrowLeft') {
          e.preventDefault()
          setSize((s) => clamp(s - step))
        }
        if (e.key === 'ArrowRight') {
          e.preventDefault()
          setSize((s) => clamp(s + step))
        }
      } else {
        if (e.key === 'ArrowUp') {
          e.preventDefault()
          setSize((s) => clamp(s - step))
        }
        if (e.key === 'ArrowDown') {
          e.preventDefault()
          setSize((s) => clamp(s + step))
        }
      }
      if (e.key === 'Home') {
        e.preventDefault()
        setSize(min)
      }
      if (e.key === 'End') {
        e.preventDefault()
        setSize(max)
      }
    },
    [orientation, min, max, clamp],
  )

  const firstStyle =
    orientation === 'vertical'
      ? { flex: `0 0 ${size}%`, minWidth: 0 }
      : { flex: `0 0 ${size}%`, minHeight: 0 }

  return (
    <div
      ref={containerRef}
      className={['rp', `rp--${orientation}`, className].filter(Boolean).join(' ')}
      style={style}
    >
      <div className="rp-pane" style={firstStyle}>
        {children[0]}
      </div>
      <div
        role="separator"
        tabIndex={0}
        aria-orientation={orientation}
        aria-valuenow={size}
        aria-valuemin={min}
        aria-valuemax={max}
        aria-label={label}
        className="rp-handle"
        onMouseDown={onMouseDown}
        onKeyDown={onKeyDown}
      />
      <div className="rp-pane rp-pane--second">{children[1]}</div>
    </div>
  )
}
