// packages/svelte/src/lib/components/Signal.svelte
<script lang="ts">
  interface Props {
    weak?: boolean;
    label?: string | undefined;
  }

  let { weak = false, label = undefined }: Props = $props();
</script>

<span
  class="signal {weak ? 'weak' : ''}"
  role="img"
  aria-label={label ?? (weak ? 'Signal: weak' : 'Signal: strong')}
>
  <i></i><i></i><i></i><i></i>
</span>

// packages/react/src/components/Signal.tsx
export interface SignalProps {
  weak?: boolean;
  label?: string;
}

export function Signal({ weak = false, label }: SignalProps) {
  return (
    <span
      className={`signal ${weak ? 'weak' : ''}`.trim()}
      role="img"
      aria-label={label ?? (weak ? 'Signal: weak' : 'Signal: strong')}
    >
      <i />
      <i />
      <i />
      <i />
    </span>
  );
}
