// packages/wc/src/elements/SkipLink.wc.svelte
<svelte:options customElement={{ tag: "uni-skip-link", extend: withShadowStyles }} />
<script>
  import Original from '@w5-ui/svelte/components/SkipLink.svelte';
  import { withShadowStyles } from '../styled.ts';
  let {
    href = '#main-content',
    class: className = ''
  } = $props();
</script>

<Original {href} class={className}>
  <slot />
</Original>

// packages/react/src/components/SkipLink.tsx
import type { AnchorHTMLAttributes } from 'react'

export interface SkipLinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  href?: string
  children?: React.ReactNode
}

export function SkipLink({
  href = '#main-content',
  children = 'Skip to main content',
  className = '',
  ...rest
}: SkipLinkProps) {
  return (
    <a className={`skip-link ${className}`.trim()} href={href} {...rest}>
      {children}
    </a>
  )
}
