// packages/svelte/src/lib/components/SkipLink.svelte
<script lang="ts">
  interface Props {
    href?: string;
    class?: string;
    children?: import('svelte').Snippet;
  }

  let { href = '#main-content', class: className = '', children }: Props = $props();
  
</script>

<a class="skip-link {className}" {href}>
  {#if children}{@render children()}{:else}Skip to main content{/if}
</a>

// packages/react/src/components/SkipLink.tsx
import type { AnchorHTMLAttributes } from 'react'

export interface SkipLinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  href?: string
  children?: React.ReactNode
}

export function SkipLink({
  href = '#main-content',
  children = 'Skip to main content',
  className = '',
  ...rest
}: SkipLinkProps) {
  return (
    <a className={`skip-link ${className}`.trim()} href={href} {...rest}>
      {children}
    </a>
  )
}
