// packages/svelte/src/lib/components/Stat.svelte
<script lang="ts">
  import Card from './Card.svelte';
  export let label: string;
  export let value: string = '';
  export let unit: string | undefined = undefined;
  export let sub: string | undefined = undefined;
  export let delta: string | undefined = undefined;
  export let deltaDir: 'up' | 'down' | 'neutral' = 'neutral';
  export let span: number | undefined = undefined;
  export let color: string | undefined = undefined;
  $: deltaClass = deltaDir === 'up' ? 'delta-up' : deltaDir === 'down' ? 'delta-down' : '';
</script>

<Card {span}>
  <h3>{label}</h3>
  <div class="stat" style={color ? `color:${color};` : ''}>
    <slot name="value">{value}</slot>{#if unit}<span class="unit">{unit}</span>{/if}
  </div>
  {#if sub || delta}
    <div class="submeta">
      {#if sub}{sub}{/if}{#if sub && delta} · {/if}{#if delta}<span class="sr-only">Trend: </span><span class={deltaClass}>{delta}</span>{/if}
    </div>
  {/if}
</Card>

// packages/react/src/components/Stat.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { Card } from './Card.js';

export interface StatProps extends Omit<HTMLAttributes<HTMLDivElement>, 'color'> {
  label: string;
  value: ReactNode;
  unit?: string;
  sub?: string;
  delta?: string;
  deltaDir?: 'up' | 'down' | 'neutral';
  span?: number;
  color?: string;
}

export function Stat({ label, value, unit, sub, delta, deltaDir = 'neutral', span, color, ...rest }: StatProps) {
  const deltaClass = deltaDir === 'up' ? 'delta-up' : deltaDir === 'down' ? 'delta-down' : '';
  return (
    <Card span={span} {...rest}>
      <h3>{label}</h3>
      <div className="stat" style={color ? { color } : undefined}>
        {value}
        {unit && <span className="unit">{unit}</span>}
      </div>
      {(sub || delta) && (
        <div className="submeta">
          {sub}
          {sub && delta && ' · '}
          {delta && (
            <>
              <span className="sr-only">Trend: </span>
              <span className={deltaClass || undefined}>{delta}</span>
            </>
          )}
        </div>
      )}
    </Card>
  );
}
