// packages/svelte/src/lib/components/StepChart.svelte
<script lang="ts">
  export interface StepChartSeries {
    label: string;
    color: string;
    values: number[];
  }

  export let series: StepChartSeries[] = [];
  export let labels: string[] = [];
  export let height: number = 160;
  export let ariaLabel: string = 'Step chart';

  const VW = 400;
  const PAD = { t: 12, r: 8, b: 28, l: 8 };

  $: allValues = series.flatMap((s) => s.values);
  $: minV = allValues.length ? Math.min(...allValues) : 0;
  $: maxV = allValues.length ? Math.max(...allValues) : 1;
  $: range = maxV - minV || 1;
  $: chartW = VW - PAD.l - PAD.r;
  $: chartH = height - PAD.t - PAD.b;
  $: n = series[0]?.values.length ?? 0;

  function toX(i: number): number {
    return PAD.l + (n > 1 ? (i / (n - 1)) * chartW : chartW / 2);
  }
  function toY(v: number): number {
    return PAD.t + chartH - ((v - minV) / range) * chartH;
  }

  function stepPath(s: StepChartSeries): string {
    if (!s.values.length) return '';
    let d = `M ${toX(0).toFixed(1)},${toY(s.values[0]).toFixed(1)}`;
    for (let i = 1; i < s.values.length; i++) {
      d += ` H ${toX(i).toFixed(1)} V ${toY(s.values[i]).toFixed(1)}`;
    }
    return d;
  }

  function stepArea(s: StepChartSeries): string {
    if (!s.values.length) return '';
    const bot = (PAD.t + chartH).toFixed(1);
    let d = `M ${toX(0).toFixed(1)},${bot} V ${toY(s.values[0]).toFixed(1)}`;
    for (let i = 1; i < s.values.length; i++) {
      d += ` H ${toX(i).toFixed(1)} V ${toY(s.values[i]).toFixed(1)}`;
    }
    d += ` H ${toX(s.values.length - 1).toFixed(1)} V ${bot} Z`;
    return d;
  }

  $: gridLines = [0, 0.25, 0.5, 0.75, 1].map((f) => PAD.t + (1 - f) * chartH);
  $: paths = series.map((s) => ({ color: s.color, label: s.label, d: stepPath(s) }));
  $: areas = series.map((s) => ({ color: s.color, label: s.label, d: stepArea(s) }));
</script>

<div role="img" aria-label={ariaLabel} style="width:100%;">
  <svg viewBox="0 0 {VW} {height}" style="width:100%;height:auto;display:block;" aria-hidden="true" focusable="false">
    {#each gridLines as y}
      <line x1={PAD.l} y1={y} x2={VW - PAD.r} y2={y} stroke="rgba(255,255,255,0.06)" stroke-width="1" />
    {/each}
    {#each areas as s (s.label)}
      <path d={s.d} fill={s.color} fill-opacity="0.1" />
    {/each}
    {#each paths as s (s.label)}
      <path d={s.d} fill="none" stroke={s.color} stroke-width="2" stroke-linejoin="round" stroke-linecap="round" />
    {/each}
    {#if labels.length > 0}
      {#each labels as lbl, i}
        {@const x = PAD.l + (labels.length > 1 ? (i / (labels.length - 1)) * chartW : chartW / 2)}
        <text x={x} y={height - 4} text-anchor="middle" fill="#6E7079" font-size="9" font-family="inherit">{lbl}</text>
      {/each}
    {/if}
  </svg>
</div>

// packages/react/src/components/StepChart.tsx
import { useMemo } from 'react'

export interface StepChartSeries {
  label: string
  color: string
  values: number[]
}

export interface StepChartProps {
  series: StepChartSeries[]
  labels?: string[]
  height?: number
  ariaLabel?: string
}

const VW = 400
const PAD = { t: 12, r: 8, b: 28, l: 8 }

function stepPath(xs: number[], ys: number[]): string {
  if (!xs.length) return ''
  let d = `M ${xs[0].toFixed(1)},${ys[0].toFixed(1)}`
  for (let i = 1; i < xs.length; i++) {
    d += ` H ${xs[i].toFixed(1)} V ${ys[i].toFixed(1)}`
  }
  return d
}

function stepArea(xs: number[], ys: number[], bot: number): string {
  if (!xs.length) return ''
  const b = bot.toFixed(1)
  let d = `M ${xs[0].toFixed(1)},${b} V ${ys[0].toFixed(1)}`
  for (let i = 1; i < xs.length; i++) {
    d += ` H ${xs[i].toFixed(1)} V ${ys[i].toFixed(1)}`
  }
  d += ` H ${xs[xs.length - 1].toFixed(1)} V ${b} Z`
  return d
}

export function StepChart({
  series,
  labels = [],
  height = 160,
  ariaLabel = 'Step chart',
}: StepChartProps) {
  const { paths, areas, gridLines } = useMemo(() => {
    const allValues = series.flatMap((s) => s.values)
    if (!allValues.length) return { paths: [], areas: [], gridLines: [] }
    const minV = Math.min(...allValues)
    const maxV = Math.max(...allValues)
    const range = maxV - minV || 1
    const chartW = VW - PAD.l - PAD.r
    const chartH = height - PAD.t - PAD.b
    const n = series[0]?.values.length ?? 0

    const toX = (i: number) => PAD.l + (n > 1 ? (i / (n - 1)) * chartW : chartW / 2)
    const toY = (v: number) => PAD.t + chartH - ((v - minV) / range) * chartH

    const gridLines = [0, 0.25, 0.5, 0.75, 1].map((f) => PAD.t + (1 - f) * chartH)
    const bot = PAD.t + chartH

    const paths = series.map((s) => {
      const xs = s.values.map((_, i) => toX(i))
      const ys = s.values.map((v) => toY(v))
      return { color: s.color, label: s.label, d: stepPath(xs, ys) }
    })

    const areas = series.map((s) => {
      const xs = s.values.map((_, i) => toX(i))
      const ys = s.values.map((v) => toY(v))
      return { color: s.color, label: s.label, d: stepArea(xs, ys, bot) }
    })

    return { paths, areas, gridLines }
  }, [series, height])

  const chartW = VW - PAD.l - PAD.r

  return (
    <div role="img" aria-label={ariaLabel} style={{ width: '100%' }}>
      <svg
        viewBox={`0 0 ${VW} ${height}`}
        style={{ width: '100%', height: 'auto', display: 'block' }}
        aria-hidden="true"
        focusable="false"
      >
        {gridLines.map((y, i) => (
          <line
            key={i}
            x1={PAD.l}
            y1={y}
            x2={VW - PAD.r}
            y2={y}
            stroke="rgba(255,255,255,0.06)"
            strokeWidth={1}
          />
        ))}
        {areas.map((s) => (
          <path key={s.label} d={s.d} fill={s.color} fillOpacity={0.1} />
        ))}
        {paths.map((s) => (
          <path
            key={s.label}
            d={s.d}
            fill="none"
            stroke={s.color}
            strokeWidth={2}
            strokeLinejoin="round"
            strokeLinecap="round"
          />
        ))}
        {labels.map((lbl, i) => {
          const x = PAD.l + (labels.length > 1 ? (i / (labels.length - 1)) * chartW : chartW / 2)
          return (
            <text
              key={i}
              x={x}
              y={height - 4}
              textAnchor="middle"
              fill="#6E7079"
              fontSize={9}
              fontFamily="inherit"
            >
              {lbl}
            </text>
          )
        })}
      </svg>
    </div>
  )
}
