// packages/svelte/src/lib/components/ToggleGroup.svelte
<script lang="ts">
  

  interface Props {
    options?: { value: string; label: string; disabled?: boolean }[];
    value?: string[];
    ariaLabel?: string;
    size?: 'sm' | 'md';
    class?: string;
    onchange?: (payload: string[]) => void;
  }

  let {
    options = [],
    value = $bindable([]),
    ariaLabel = '',
    size = 'md',
    class: klass = '',
    onchange,
  }: Props = $props();
  function toggle(v: string) {
    const next = value.includes(v) ? value.filter((x) => x !== v) : [...value, v];
    value = next;
    onchange?.(next);
  }
</script>

<div role="group" aria-label={ariaLabel} class="tg-group tg-group--{size}{klass ? ` ${klass}` : ''}">
  {#each options as opt}
    <button
      type="button"
      aria-pressed={value.includes(opt.value)}
      disabled={opt.disabled}
      class="tg-btn{value.includes(opt.value) ? ' tg-btn--on' : ''}"
      onclick={() => toggle(opt.value)}
    >
      {opt.label}
    </button>
  {/each}
</div>

// packages/react/src/components/ToggleGroup.tsx
import type { ReactNode } from 'react'

export interface ToggleGroupOption {
  value: string
  label: ReactNode
  disabled?: boolean
}

export interface ToggleGroupProps {
  options: ToggleGroupOption[]
  value: string[]
  onChange: (value: string[]) => void
  ariaLabel: string
  size?: 'sm' | 'md'
  className?: string
}

export function ToggleGroup({
  options,
  value,
  onChange,
  ariaLabel,
  size = 'md',
  className = '',
}: ToggleGroupProps) {
  function toggle(v: string) {
    if (value.includes(v)) {
      onChange(value.filter((x) => x !== v))
    } else {
      onChange([...value, v])
    }
  }

  return (
    <div
      role="group"
      aria-label={ariaLabel}
      className={`tg-group tg-group--${size}${className ? ` ${className}` : ''}`}
    >
      {options.map((opt) => {
        const pressed = value.includes(opt.value)
        return (
          <button
            key={opt.value}
            type="button"
            aria-pressed={pressed}
            disabled={opt.disabled}
            className={`tg-btn${pressed ? ' tg-btn--on' : ''}`}
            onClick={() => toggle(opt.value)}
          >
            {opt.label}
          </button>
        )
      })}
    </div>
  )
}
