// packages/svelte/src/lib/components/Tooltip.svelte
<script module lang="ts">
  let counter = 0;
</script>

<script lang="ts">
  interface Props {
    label: string;
    placement?: 'top' | 'bottom' | 'left' | 'right';
    class?: string;
    children?: import('svelte').Snippet;
  }

  let {
    label,
    placement = 'top',
    class: className = '',
    children
  }: Props = $props();
  
  const id = `dash-ui-tooltip-${++counter}`;
</script>

<span class="tooltip-wrapper tooltip-{placement} {className}">
  <span class="tooltip-trigger" aria-describedby={id}>{@render children?.()}</span>
  <span {id} role="tooltip" class="tooltip-content">{label}</span>
</span>

// packages/react/src/components/Tooltip.tsx
import type { ReactNode } from 'react';
import { useId } from 'react';

export type TooltipPlacement = 'top' | 'bottom' | 'left' | 'right';

export interface TooltipProps {
  label: string;
  children: ReactNode;
  placement?: TooltipPlacement;
  className?: string;
}

export function Tooltip({ label, children, placement = 'top', className = '' }: TooltipProps) {
  const id = useId();
  return (
    <span className={`tooltip-wrapper tooltip-${placement} ${className}`.trim()}>
      <span className="tooltip-trigger" aria-describedby={id}>{children}</span>
      <span id={id} role="tooltip" className="tooltip-content">{label}</span>
    </span>
  );
}
