// packages/svelte/src/lib/components/TransferList.svelte
<script module lang="ts">
  export interface TransferListItem {
    id: string;
    label: string;
    description?: string;
  }
</script>

<script lang="ts">
  interface Props {
    sourceLabel?: string;
    targetLabel?: string;
    source?: TransferListItem[];
    target?: TransferListItem[];
    class?: string;
    onchange?: (payload: { source: TransferListItem[]; target: TransferListItem[] }) => void;
  }

  let {
    sourceLabel = 'Available',
    targetLabel = 'Selected',
    source = $bindable([]),
    target = $bindable([]),
    class: className = '',
    onchange,
  }: Props = $props();

  let selSrc = $state(new Set<string>());
  let selTgt = $state(new Set<string>());
  let focSrc = $state(0);
  let focTgt = $state(0);
  let srcEls: (HTMLLIElement | null)[] = $state([]);
  let tgtEls: (HTMLLIElement | null)[] = $state([]);

  function commit() {
    onchange?.({ source, target });
  }

  function moveRight(ids: Set<string>) {
    if (!ids.size) return;
    const moving = source.filter((i) => ids.has(i.id));
    source = source.filter((i) => !ids.has(i.id));
    target = [...target, ...moving];
    selSrc = new Set();
    focSrc = 0;
    commit();
  }

  function moveLeft(ids: Set<string>) {
    if (!ids.size) return;
    const moving = target.filter((i) => ids.has(i.id));
    target = target.filter((i) => !ids.has(i.id));
    source = [...source, ...moving];
    selTgt = new Set();
    focTgt = 0;
    commit();
  }

  function toggleSrc(id: string) {
    const n = new Set(selSrc);
    n.has(id) ? n.delete(id) : n.add(id);
    selSrc = n;
  }

  function toggleTgt(id: string) {
    const n = new Set(selTgt);
    n.has(id) ? n.delete(id) : n.add(id);
    selTgt = n;
  }

  function srcKey(e: KeyboardEvent) {
    if (!source.length) return;
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      focSrc = Math.min(focSrc + 1, source.length - 1);
      srcEls[focSrc]?.focus();
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      focSrc = Math.max(focSrc - 1, 0);
      srcEls[focSrc]?.focus();
    } else if (e.key === ' ') {
      e.preventDefault();
      const item = source[focSrc];
      if (item) toggleSrc(item.id);
    } else if (e.key === 'Enter') {
      e.preventDefault();
      moveRight(selSrc);
    }
  }

  function tgtKey(e: KeyboardEvent) {
    if (!target.length) return;
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      focTgt = Math.min(focTgt + 1, target.length - 1);
      tgtEls[focTgt]?.focus();
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      focTgt = Math.max(focTgt - 1, 0);
      tgtEls[focTgt]?.focus();
    } else if (e.key === ' ') {
      e.preventDefault();
      const item = target[focTgt];
      if (item) toggleTgt(item.id);
    } else if (e.key === 'Enter') {
      e.preventDefault();
      moveLeft(selTgt);
    }
  }
</script>

<div class="tl {className}">
  <div class="tl__panel">
    <div class="tl__header">
      {sourceLabel} <span class="tl__count">{source.length}</span>
    </div>
    <ul
      role="listbox"
      aria-label={sourceLabel}
      aria-multiselectable="true"
      class="tl__list"
      onkeydown={srcKey}
    >
      {#if source.length === 0}
        <li class="tl__empty" role="option" aria-selected="false" aria-disabled="true">Empty</li>
      {:else}
        {#each source as item, i (item.id)}
          <li
            bind:this={srcEls[i]}
            role="option"
            aria-selected={selSrc.has(item.id)}
            tabindex={i === focSrc ? 0 : -1}
            class="tl__item{selSrc.has(item.id) ? ' tl__item--sel' : ''}"
            onclick={() => { focSrc = i; toggleSrc(item.id); }}
            onkeydown={(e) => { if (e.key === ' ') { e.preventDefault(); focSrc = i; toggleSrc(item.id); } }}
          >
            <span class="tl__item-label">{item.label}</span>
            {#if item.description}<span class="tl__item-desc">{item.description}</span>{/if}
          </li>
        {/each}
      {/if}
    </ul>
  </div>

  <div class="tl__controls" role="group" aria-label="Transfer controls">
    <button type="button" class="tl__btn" aria-label="Move all to {targetLabel}"
      disabled={source.length === 0}
      onclick={() => moveRight(new Set(source.map((i) => i.id)))}>»</button>
    <button type="button" class="tl__btn" aria-label="Move selected to {targetLabel}"
      disabled={selSrc.size === 0}
      onclick={() => moveRight(selSrc)}>›</button>
    <button type="button" class="tl__btn" aria-label="Move selected back to {sourceLabel}"
      disabled={selTgt.size === 0}
      onclick={() => moveLeft(selTgt)}>‹</button>
    <button type="button" class="tl__btn" aria-label="Move all back to {sourceLabel}"
      disabled={target.length === 0}
      onclick={() => moveLeft(new Set(target.map((i) => i.id)))}>«</button>
  </div>

  <div class="tl__panel">
    <div class="tl__header">
      {targetLabel} <span class="tl__count">{target.length}</span>
    </div>
    <ul
      role="listbox"
      aria-label={targetLabel}
      aria-multiselectable="true"
      class="tl__list"
      onkeydown={tgtKey}
    >
      {#if target.length === 0}
        <li class="tl__empty" role="option" aria-selected="false" aria-disabled="true">Empty</li>
      {:else}
        {#each target as item, i (item.id)}
          <li
            bind:this={tgtEls[i]}
            role="option"
            aria-selected={selTgt.has(item.id)}
            tabindex={i === focTgt ? 0 : -1}
            class="tl__item{selTgt.has(item.id) ? ' tl__item--sel' : ''}"
            onclick={() => { focTgt = i; toggleTgt(item.id); }}
            onkeydown={(e) => { if (e.key === ' ') { e.preventDefault(); focTgt = i; toggleTgt(item.id); } }}
          >
            <span class="tl__item-label">{item.label}</span>
            {#if item.description}<span class="tl__item-desc">{item.description}</span>{/if}
          </li>
        {/each}
      {/if}
    </ul>
  </div>
</div>

// packages/react/src/components/TransferList.tsx
import { useId, useRef, useState } from 'react'

export interface TransferListItem {
  id: string
  label: string
  description?: string
}

export interface TransferListProps {
  sourceLabel?: string
  targetLabel?: string
  source?: TransferListItem[]
  target?: TransferListItem[]
  defaultSource?: TransferListItem[]
  defaultTarget?: TransferListItem[]
  onChange?: (source: TransferListItem[], target: TransferListItem[]) => void
  className?: string
}

export function TransferList({
  sourceLabel = 'Available',
  targetLabel = 'Selected',
  source: srcProp,
  target: tgtProp,
  defaultSource = [],
  defaultTarget = [],
  onChange,
  className = '',
}: TransferListProps) {
  const gid = useId()
  const [intSrc, setIntSrc] = useState<TransferListItem[]>(() => srcProp ?? defaultSource)
  const [intTgt, setIntTgt] = useState<TransferListItem[]>(() => tgtProp ?? defaultTarget)
  const srcItems = srcProp !== undefined ? srcProp : intSrc
  const tgtItems = tgtProp !== undefined ? tgtProp : intTgt

  const [selSrc, setSelSrc] = useState(new Set<string>())
  const [selTgt, setSelTgt] = useState(new Set<string>())
  const [focSrc, setFocSrc] = useState(0)
  const [focTgt, setFocTgt] = useState(0)
  const srcRefs = useRef<(HTMLLIElement | null)[]>([])
  const tgtRefs = useRef<(HTMLLIElement | null)[]>([])

  function commit(nextSrc: TransferListItem[], nextTgt: TransferListItem[]) {
    if (srcProp === undefined) setIntSrc(nextSrc)
    if (tgtProp === undefined) setIntTgt(nextTgt)
    onChange?.(nextSrc, nextTgt)
  }

  function moveRight(ids: Set<string>) {
    if (!ids.size) return
    commit(
      srcItems.filter((i) => !ids.has(i.id)),
      [...tgtItems, ...srcItems.filter((i) => ids.has(i.id))],
    )
    setSelSrc(new Set())
    setFocSrc(0)
  }

  function moveLeft(ids: Set<string>) {
    if (!ids.size) return
    commit(
      [...srcItems, ...tgtItems.filter((i) => ids.has(i.id))],
      tgtItems.filter((i) => !ids.has(i.id)),
    )
    setSelTgt(new Set())
    setFocTgt(0)
  }

  function toggle(sel: Set<string>, set: (s: Set<string>) => void, id: string) {
    const n = new Set(sel)
    if (n.has(id)) {
      n.delete(id)
    } else {
      n.add(id)
    }
    set(n)
  }

  function listKey(
    e: React.KeyboardEvent,
    items: TransferListItem[],
    sel: Set<string>,
    setSel: (s: Set<string>) => void,
    foc: number,
    setFoc: (n: number) => void,
    refs: React.MutableRefObject<(HTMLLIElement | null)[]>,
    onEnter: () => void,
  ) {
    if (!items.length) return
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      const n = Math.min(foc + 1, items.length - 1)
      setFoc(n)
      refs.current[n]?.focus()
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      const n = Math.max(foc - 1, 0)
      setFoc(n)
      refs.current[n]?.focus()
    } else if (e.key === ' ') {
      e.preventDefault()
      const item = items[foc]
      if (item) toggle(sel, setSel, item.id)
    } else if (e.key === 'Enter') {
      e.preventDefault()
      onEnter()
    }
  }

  function renderList(
    id: string,
    label: string,
    items: TransferListItem[],
    sel: Set<string>,
    setSel: (s: Set<string>) => void,
    foc: number,
    setFoc: (n: number) => void,
    refs: React.MutableRefObject<(HTMLLIElement | null)[]>,
    onEnter: () => void,
  ) {
    return (
      <div className="tl__panel">
        <div className="tl__header" id={id}>
          {label} <span className="tl__count">{items.length}</span>
        </div>
        <ul
          role="listbox"
          aria-labelledby={id}
          aria-multiselectable="true"
          className="tl__list"
          onKeyDown={(e) => listKey(e, items, sel, setSel, foc, setFoc, refs, onEnter)}
        >
          {items.length === 0 ? (
            <li className="tl__empty" role="option" aria-selected={false} aria-disabled="true">
              Empty
            </li>
          ) : (
            items.map((item, i) => (
              <li
                key={item.id}
                ref={(el) => {
                  refs.current[i] = el
                }}
                role="option"
                aria-selected={sel.has(item.id)}
                tabIndex={i === foc ? 0 : -1}
                className={`tl__item${sel.has(item.id) ? ' tl__item--sel' : ''}`}
                onClick={() => {
                  setFoc(i)
                  toggle(sel, setSel, item.id)
                }}
              >
                <span className="tl__item-label">{item.label}</span>
                {item.description && <span className="tl__item-desc">{item.description}</span>}
              </li>
            ))
          )}
        </ul>
      </div>
    )
  }

  return (
    <div className={`tl ${className}`.trim()}>
      {renderList(
        `${gid}-src`,
        sourceLabel,
        srcItems,
        selSrc,
        setSelSrc,
        focSrc,
        setFocSrc,
        srcRefs,
        () => moveRight(selSrc),
      )}
      <div className="tl__controls" role="group" aria-label="Transfer controls">
        <button
          type="button"
          className="tl__btn"
          aria-label={`Move all to ${targetLabel}`}
          disabled={!srcItems.length}
          onClick={() => moveRight(new Set(srcItems.map((i) => i.id)))}
        >
          {'»'}
        </button>
        <button
          type="button"
          className="tl__btn"
          aria-label={`Move selected to ${targetLabel}`}
          disabled={!selSrc.size}
          onClick={() => moveRight(selSrc)}
        >
          {'›'}
        </button>
        <button
          type="button"
          className="tl__btn"
          aria-label={`Move selected back to ${sourceLabel}`}
          disabled={!selTgt.size}
          onClick={() => moveLeft(selTgt)}
        >
          {'‹'}
        </button>
        <button
          type="button"
          className="tl__btn"
          aria-label={`Move all back to ${sourceLabel}`}
          disabled={!tgtItems.length}
          onClick={() => moveLeft(new Set(tgtItems.map((i) => i.id)))}
        >
          {'«'}
        </button>
      </div>
      {renderList(
        `${gid}-tgt`,
        targetLabel,
        tgtItems,
        selTgt,
        setSelTgt,
        focTgt,
        setFocTgt,
        tgtRefs,
        () => moveLeft(selTgt),
      )}
    </div>
  )
}
