// packages/svelte/src/lib/components/VirtualList.svelte
<script lang="ts">
  export let items: unknown[] = [];
  export let itemHeight: number = 48;
  export let height: number = 400;
  export let label: string | undefined = undefined;
  export let overscan: number = 3;

  let scrollTop = 0;

  $: totalHeight = items.length * itemHeight;
  $: firstVisible = Math.floor(scrollTop / itemHeight);
  $: startIndex = Math.max(0, firstVisible - overscan);
  $: endIndex = Math.min(items.length, firstVisible + Math.ceil(height / itemHeight) + overscan + 1);
  $: visible = items.slice(startIndex, endIndex).map((item, i) => ({ item, index: startIndex + i }));
</script>

<div
  role="list"
  aria-label={label}
  class="vl"
  style:height="{height}px"
  style:overflow-y="auto"
  on:scroll={(e) => (scrollTop = e.currentTarget.scrollTop)}
>
  <div style:height="{totalHeight}px" style:position="relative">
    <div style:position="absolute" style:top="{startIndex * itemHeight}px" style:width="100%">
      {#each visible as { item, index } (index)}
        <div
          role="listitem"
          style:height="{itemHeight}px"
          style:overflow="hidden"
        >
          <slot {item} {index} />
        </div>
      {/each}
    </div>
  </div>
</div>

// packages/react/src/components/VirtualList.tsx
import { useState, useCallback, type ReactNode } from 'react'

export interface VirtualListProps<T> {
  items: T[]
  itemHeight: number
  height: number
  renderItem: (item: T, index: number) => ReactNode
  overscan?: number
  label?: string
  className?: string
}

export function VirtualList<T>({
  items,
  itemHeight,
  height,
  renderItem,
  overscan = 3,
  label,
  className,
}: VirtualListProps<T>) {
  const [scrollTop, setScrollTop] = useState(0)

  const totalHeight = items.length * itemHeight
  const firstVisible = Math.floor(scrollTop / itemHeight)
  const startIndex = Math.max(0, firstVisible - overscan)
  const endIndex = Math.min(
    items.length,
    firstVisible + Math.ceil(height / itemHeight) + overscan + 1,
  )

  const handleScroll = useCallback((e: React.UIEvent<HTMLDivElement>) => {
    setScrollTop(e.currentTarget.scrollTop)
  }, [])

  return (
    <div
      role="list"
      aria-label={label}
      className={['vl', className].filter(Boolean).join(' ')}
      style={{ height, overflowY: 'auto' }}
      onScroll={handleScroll}
    >
      <div style={{ height: totalHeight, position: 'relative' }}>
        <div style={{ position: 'absolute', top: startIndex * itemHeight, width: '100%' }}>
          {items.slice(startIndex, endIndex).map((item, i) => (
            <div
              key={startIndex + i}
              role="listitem"
              style={{ height: itemHeight, overflow: 'hidden' }}
            >
              {renderItem(item, startIndex + i)}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
