// packages/react/src/components/Badge.tsx
import type { ReactNode } from 'react';

export type BadgeColor = 'danger' | 'warn' | 'info' | 'success' | 'neutral';

export interface BadgeProps {
  children: ReactNode;
  count?: number;
  dot?: boolean;
  max?: number;
  showZero?: boolean;
  color?: BadgeColor;
  className?: string;
}

export function Badge({
  children,
  count,
  dot = false,
  max = 99,
  showZero = false,
  color = 'danger',
  className = '',
}: BadgeProps) {
  const show = dot || (count !== undefined && (showZero || count > 0));
  const label = count !== undefined ? (count > max ? `${max}+` : String(count)) : '';
  return (
    <span className={`badge-wrapper${className ? ` ${className}` : ''}`}>
      {children}
      {show && (
        <span className={`badge badge-${color}${dot ? ' badge-dot' : ''}`} aria-hidden="true">
          {!dot && label}
        </span>
      )}
    </span>
  );
}

// packages/wc/src/elements/Badge.wc.svelte
<svelte:options customElement="uni-badge" />
<script>
  import Original from '@w5-ui/svelte/components/Badge.svelte';
  let {
    count = undefined,
    dot = false,
    max = 99,
    showZero = false,
    color = 'danger',
    class: klass = ''
  } = $props();
</script>

<Original {count} {dot} {max} {showZero} {color} class={klass}>
  <slot />
</Original>
