// packages/react/src/components/ToggleGroup.tsx
import type { ReactNode } from 'react'

export interface ToggleGroupOption {
  value: string
  label: ReactNode
  disabled?: boolean
}

export interface ToggleGroupProps {
  options: ToggleGroupOption[]
  value: string[]
  onChange: (value: string[]) => void
  ariaLabel: string
  size?: 'sm' | 'md'
  className?: string
}

export function ToggleGroup({
  options,
  value,
  onChange,
  ariaLabel,
  size = 'md',
  className = '',
}: ToggleGroupProps) {
  function toggle(v: string) {
    if (value.includes(v)) {
      onChange(value.filter((x) => x !== v))
    } else {
      onChange([...value, v])
    }
  }

  return (
    <div
      role="group"
      aria-label={ariaLabel}
      className={`tg-group tg-group--${size}${className ? ` ${className}` : ''}`}
    >
      {options.map((opt) => {
        const pressed = value.includes(opt.value)
        return (
          <button
            key={opt.value}
            type="button"
            aria-pressed={pressed}
            disabled={opt.disabled}
            className={`tg-btn${pressed ? ' tg-btn--on' : ''}`}
            onClick={() => toggle(opt.value)}
          >
            {opt.label}
          </button>
        )
      })}
    </div>
  )
}

// packages/wc/src/elements/ToggleGroup.wc.svelte
<svelte:options customElement="uni-toggle-group" />
<script>
  import Original from '@w5-ui/svelte/components/ToggleGroup.svelte';
  export let options = [];
  export let value = [];
  export let ariaLabel = '';
  export let size = 'md';
</script>

<Original {options} {value} {ariaLabel} {size}>
  <slot />
</Original>
